-- begin SUBROGADOR
alter table SUBROGADOR add constraint FK_SUBROGADOR_ON_CONTRATO_INQUILINO foreign key (CONTRATO_INQUILINO_ID) references CONTRATO_INQUILINO(ID)^
alter table SUBROGADOR add constraint FK_SUBROGADOR_ON_SUBROGADOR foreign key (SUBROGADOR_ID) references PERSONA(ID)^
create index IDX_SUBROGADOR_ON_CONTRATO_INQUILINO on SUBROGADOR (CONTRATO_INQUILINO_ID)^
create index IDX_SUBROGADOR_ON_SUBROGADOR on SUBROGADOR (SUBROGADOR_ID)^
-- end SUBROGADOR
-- begin LIQUIDACION_SUSCRIPCION
alter table LIQUIDACION_SUSCRIPCION add constraint FK_LIQUIDACION_SUSCRIPCION_ON_ESCANEO_LIQUIDACION foreign key (ESCANEO_LIQUIDACION_ID) references ARCHIVO_ADJUNTO(ID)^
alter table LIQUIDACION_SUSCRIPCION add constraint FK_LIQUIDACION_SUSCRIPCION_ON_ESCANEO_INGRESO_LIQUIDACION foreign key (ESCANEO_INGRESO_LIQUIDACION_ID) references ARCHIVO_ADJUNTO(ID)^
alter table LIQUIDACION_SUSCRIPCION add constraint FK_LIQUIDACION_SUSCRIPCION_ON_CONTRATO_INQUILINO foreign key (CONTRATO_INQUILINO_ID) references CONTRATO_INQUILINO(ID)^
alter table LIQUIDACION_SUSCRIPCION add constraint FK_LIQUIDACION_SUSCRIPCION_ON_ESCANEO_RESGUARDO_ITP foreign key (ESCANEO_RESGUARDO_ITP_ID) references ARCHIVO_ADJUNTO(ID)^
create index IDX_LIQUIDACION_SUSCRIPCION_ON_ESCANEO_LIQUIDACION on LIQUIDACION_SUSCRIPCION (ESCANEO_LIQUIDACION_ID)^
create index IDX_LIQUIDACION_SUSCRIPCION_ON_ESCANEO_INGRESO_LIQUIDACION on LIQUIDACION_SUSCRIPCION (ESCANEO_INGRESO_LIQUIDACION_ID)^
create index IDX_LIQUIDACION_SUSCRIPCION_ON_CONTRATO_INQUILINO on LIQUIDACION_SUSCRIPCION (CONTRATO_INQUILINO_ID)^
create index IDX_LIQUIDACION_SUSCRIPCION_ON_ESCANEO_RESGUARDO_ITP on LIQUIDACION_SUSCRIPCION (ESCANEO_RESGUARDO_ITP_ID)^
-- end LIQUIDACION_SUSCRIPCION
-- begin PARAMETRO_VALOR
alter table PARAMETRO_VALOR add constraint FK_PARAMETRO_VALOR_ON_IMPLEMENTACION_MODELO foreign key (IMPLEMENTACION_MODELO_ID) references IMPLEMENTACION_MODELO(ID)^
create index IDX_PARAMETRO_VALOR_ON_IMPLEMENTACION_MODELO on PARAMETRO_VALOR (IMPLEMENTACION_MODELO_ID)^
-- end PARAMETRO_VALOR
-- begin ANEXO
alter table ANEXO add constraint FK_ANEXO_ON_PLANTILLA foreign key (PLANTILLA_ID) references PLANTILLA(ID)^
alter table ANEXO add constraint FK_ANEXO_ON_CONTRATO_INQUILINO foreign key (CONTRATO_INQUILINO_ID) references CONTRATO_INQUILINO(ID)^
create index IDX_ANEXO_ON_PLANTILLA on ANEXO (PLANTILLA_ID)^
create index IDX_ANEXO_ON_CONTRATO_INQUILINO on ANEXO (CONTRATO_INQUILINO_ID)^
-- end ANEXO
-- begin VERSION_CLAUSULA
alter table VERSION_CLAUSULA add constraint FK_VERSION_CLAUSULA_ON_CLAUSULA foreign key (CLAUSULA_ID) references CLAUSULA(ID)^
create index IDX_VERSION_CLAUSULA_ON_CLAUSULA on VERSION_CLAUSULA (CLAUSULA_ID)^
-- end VERSION_CLAUSULA
-- begin DEPARTAMENTO
alter table DEPARTAMENTO add constraint FK_DEPARTAMENTO_ON_COLECCION_ADJUNTOS foreign key (COLECCION_ADJUNTOS_ID) references COLECCION_ARCHIVOS_ADJUNTOS(ID)^
alter table DEPARTAMENTO add constraint FK_DEPARTAMENTO_ON_PROPIETARIO foreign key (PROPIETARIO_ID) references PROPIETARIO(ID)^
alter table DEPARTAMENTO add constraint FK_DEPARTAMENTO_ON_UBICACION foreign key (UBICACION_ID) references UBICACION(ID)^
alter table DEPARTAMENTO add constraint FK_DEPARTAMENTO_ON_PLANO_DEPARTAMENTO foreign key (PLANO_DEPARTAMENTO_ID) references ARCHIVO_ADJUNTO(ID)^
create index IDX_DEPARTAMENTO_ON_COLECCION_ADJUNTOS on DEPARTAMENTO (COLECCION_ADJUNTOS_ID)^
create index IDX_DEPARTAMENTO_ON_PROPIETARIO on DEPARTAMENTO (PROPIETARIO_ID)^
create index IDX_DEPARTAMENTO_ON_UBICACION on DEPARTAMENTO (UBICACION_ID)^
create index IDX_DEPARTAMENTO_ON_PLANO_DEPARTAMENTO on DEPARTAMENTO (PLANO_DEPARTAMENTO_ID)^
-- end DEPARTAMENTO
-- begin NOTIFICACION
alter table NOTIFICACION add constraint FK_NOTIFICACION_ON_PLANTILLA foreign key (PLANTILLA_ID) references PLANTILLA(ID)^
alter table NOTIFICACION add constraint FK_NOTIFICACION_ON_CONTRATO_INQUILINO foreign key (CONTRATO_INQUILINO_ID) references CONTRATO_INQUILINO(ID)^
create index IDX_NOTIFICACION_ON_PLANTILLA on NOTIFICACION (PLANTILLA_ID)^
create index IDX_NOTIFICACION_ON_CONTRATO_INQUILINO on NOTIFICACION (CONTRATO_INQUILINO_ID)^
-- end NOTIFICACION
-- begin PROVEEDOR
alter table PROVEEDOR add constraint FK_PROVEEDOR_ON_PERSONA foreign key (PERSONA_ID) references PERSONA(ID)^
alter table PROVEEDOR add constraint FK_PROVEEDOR_ON_CUENTA_BANCARIA foreign key (CUENTA_BANCARIA_ID) references CUENTA_BANCARIA(ID)^
alter table PROVEEDOR add constraint FK_PROVEEDOR_ON_CUENTA_BANCARIA_DOMICILIADO foreign key (CUENTA_BANCARIA_DOMICILIADO_ID) references CUENTA_BANCARIA(ID)^
create index IDX_PROVEEDOR_ON_PERSONA on PROVEEDOR (PERSONA_ID)^
create index IDX_PROVEEDOR_ON_CUENTA_BANCARIA on PROVEEDOR (CUENTA_BANCARIA_ID)^
create index IDX_PROVEEDOR_ON_CUENTA_BANCARIA_DOMICILIADO on PROVEEDOR (CUENTA_BANCARIA_DOMICILIADO_ID)^
-- end PROVEEDOR
-- begin TEST1_FOTO_THUMBNAIL
alter table TEST1_FOTO_THUMBNAIL add constraint FK_TEST1_FOTO_THUMBNAIL_ON_CARPETA_DOCUMENTO_FOTOGRAFICO foreign key (CARPETA_DOCUMENTO_FOTOGRAFICO_ID) references CTA_DOCTOS_FOTOGRAFICOS(ID)^
create index IDX_TEST1_FOTO_THUMBNAIL_ON_CARPETA_DOCUMENTO_FOTOGRAFICO on TEST1_FOTO_THUMBNAIL (CARPETA_DOCUMENTO_FOTOGRAFICO_ID)^
-- end TEST1_FOTO_THUMBNAIL
-- begin DATO_DE_CONTACTO
alter table DATO_DE_CONTACTO add constraint FK_DATO_DE_CONTACTO_ON_PERSONA foreign key (PERSONA_ID) references PERSONA(ID)^
create index IDX_DATO_DE_CONTACTO_ON_PERSONA on DATO_DE_CONTACTO (PERSONA_ID)^
-- end DATO_DE_CONTACTO
-- begin CUENTA_BANCARIA
alter table CUENTA_BANCARIA add constraint FK_CUENTA_BANCARIA_ON_PERSONA foreign key (PERSONA_ID) references PERSONA(ID)^
create index IDX_CUENTA_BANCARIA_ON_PERSONA on CUENTA_BANCARIA (PERSONA_ID)^
-- end CUENTA_BANCARIA
-- begin RTRO_APP_CONCEPTO_ADICIONAL
alter table RTRO_APP_CONCEPTO_ADICIONAL add constraint FK_RTRO_APP_CONCEPTO_ADICIONAL_ON_CONCEPTO_ADICIONAL foreign key (CONCEPTO_ADICIONAL_ID) references CONCEPTO_ADICIONAL(ID)^
alter table RTRO_APP_CONCEPTO_ADICIONAL add constraint FK_RTRO_APP_CONCEPTO_ADICIONAL_ON_DOCUMENTO_IMPUTABLE foreign key (DOCUMENTO_IMPUTABLE_ID) references DOCUMENTO_IMPUTABLE(ID)^
alter table RTRO_APP_CONCEPTO_ADICIONAL add constraint FK_RTRO_APP_CONCEPTO_ADICIONAL_ON_IMPLEMENTACION_CONCEPTO foreign key (IMPLEMENTACION_CONCEPTO_ID) references IMPLEMENTACION_CONCEPTO(ID)^
create index IDX_RTRO_APP_CONCEPTO_ADICIONAL_ON_CONCEPTO_ADICIONAL on RTRO_APP_CONCEPTO_ADICIONAL (CONCEPTO_ADICIONAL_ID)^
create index IDX_RTRO_APP_CONCEPTO_ADICIONAL_ON_DOCUMENTO_IMPUTABLE on RTRO_APP_CONCEPTO_ADICIONAL (DOCUMENTO_IMPUTABLE_ID)^
create index IDX_RTRO_APP_CONCEPTO_ADICIONAL_ON_IMPLEMENTACION_CONCEPTO on RTRO_APP_CONCEPTO_ADICIONAL (IMPLEMENTACION_CONCEPTO_ID)^
-- end RTRO_APP_CONCEPTO_ADICIONAL
-- begin DIRECCION
alter table DIRECCION add constraint FK_DIRECCION_ON_PERSONA foreign key (PERSONA_ID) references PERSONA(ID)^
create index IDX_DIRECCION_ON_PERSONA on DIRECCION (PERSONA_ID)^
-- end DIRECCION
-- begin COLECCION_ARCHIVOS_ADJUNTOS
alter table COLECCION_ARCHIVOS_ADJUNTOS add constraint FK_COLECCION_ARCHIVOS_ADJUNTOS_ON_COLECCION_PARENT foreign key (COLECCION_PARENT_ID) references COLECCION_ARCHIVOS_ADJUNTOS(ID)^
create index IDX_COLECCION_ARCHIVOS_ADJUNTOS_ON_COLECCION_PARENT on COLECCION_ARCHIVOS_ADJUNTOS (COLECCION_PARENT_ID)^
-- end COLECCION_ARCHIVOS_ADJUNTOS
-- begin IMPLEMENTACION_CONCEPTO
alter table IMPLEMENTACION_CONCEPTO add constraint FK_IMPLEMENTACION_CONCEPTO_ON_CONCEPTO_RECIBO foreign key (CONCEPTO_RECIBO_ID) references CONCEPTO_RECIBO(ID)^
alter table IMPLEMENTACION_CONCEPTO add constraint FK_IMPLEMENTACION_CONCEPTO_ON_RECIBO foreign key (RECIBO_ID) references RECIBO(ID)^
alter table IMPLEMENTACION_CONCEPTO add constraint FK_IMPLEMENTACION_CONCEPTO_ON_OVERRIDE_CONCEPTO foreign key (OVERRIDE_CONCEPTO_ID) references CONCEPTO(ID)^
create index IDX_IMPLEMENTACION_CONCEPTO_ON_CONCEPTO_RECIBO on IMPLEMENTACION_CONCEPTO (CONCEPTO_RECIBO_ID)^
create index IDX_IMPLEMENTACION_CONCEPTO_ON_RECIBO on IMPLEMENTACION_CONCEPTO (RECIBO_ID)^
create index IDX_IMPLEMENTACION_CONCEPTO_ON_OVERRIDE_CONCEPTO on IMPLEMENTACION_CONCEPTO (OVERRIDE_CONCEPTO_ID)^
-- end IMPLEMENTACION_CONCEPTO
-- begin IMPLEMENTACION_MODELO
alter table IMPLEMENTACION_MODELO add constraint FK_IMPLEMENTACION_MODELO_ON_MODELO_CONTRATO foreign key (MODELO_CONTRATO_ID) references MODELO_CONTRATO(ID)^
create index IDX_IMPLEMENTACION_MODELO_ON_MODELO_CONTRATO on IMPLEMENTACION_MODELO (MODELO_CONTRATO_ID)^
-- end IMPLEMENTACION_MODELO
-- begin PERSONA
alter table PERSONA add constraint FK_PERSONA_ON_USUARIO foreign key (USUARIO_ID) references SEC_USER(ID)^
create index IDX_PERSONA_ON_USUARIO on PERSONA (USUARIO_ID)^
-- end PERSONA
-- begin DOCUMENTO_IMPUTABLE
alter table DOCUMENTO_IMPUTABLE add constraint FK_DOCUMENTO_IMPUTABLE_ON_COLECCION_ARCHIVOS_ADJUNTOS foreign key (COLECCION_ARCHIVOS_ADJUNTOS_ID) references COLECCION_ARCHIVOS_ADJUNTOS(ID)^
alter table DOCUMENTO_IMPUTABLE add constraint FK_DOCUMENTO_IMPUTABLE_ON_PROVEEDOR foreign key (PROVEEDOR_ID) references PROVEEDOR(ID)^
alter table DOCUMENTO_IMPUTABLE add constraint FK_DOCUMENTO_IMPUTABLE_ON_TITULAR_PERSONA foreign key (TITULAR_PERSONA_ID) references PERSONA(ID)^
alter table DOCUMENTO_IMPUTABLE add constraint FK_DOCUMENTO_IMPUTABLE_ON_PRESUPUESTO foreign key (PRESUPUESTO_ID) references DOCUMENTO_IMPUTABLE(ID)^
create index IDX_DOCUMENTO_IMPUTABLE_ON_COLECCION_ARCHIVOS_ADJUNTOS on DOCUMENTO_IMPUTABLE (COLECCION_ARCHIVOS_ADJUNTOS_ID)^
create index IDX_DOCUMENTO_IMPUTABLE_ON_PROVEEDOR on DOCUMENTO_IMPUTABLE (PROVEEDOR_ID)^
create index IDX_DOCUMENTO_IMPUTABLE_ON_TITULAR_PERSONA on DOCUMENTO_IMPUTABLE (TITULAR_PERSONA_ID)^
create index IDX_DOCUMENTO_IMPUTABLE_ON_PRESUPUESTO on DOCUMENTO_IMPUTABLE (PRESUPUESTO_ID)^
-- end DOCUMENTO_IMPUTABLE
-- begin CONCEPTO
alter table CONCEPTO add constraint FK_CONCEPTO_ON_MASTER_CONCEPTO foreign key (MASTER_CONCEPTO_ID) references CONCEPTO(ID)^
create index IDX_CONCEPTO_ON_MASTER_CONCEPTO on CONCEPTO (MASTER_CONCEPTO_ID)^
-- end CONCEPTO
-- begin TEST1_SECCION_DESCARTADA
alter table TEST1_SECCION_DESCARTADA add constraint FK_TEST1_SECCION_DESCARTADA_ON_SECCION foreign key (SECCION_ID) references SECCION(ID)^
alter table TEST1_SECCION_DESCARTADA add constraint FK_TEST1_SECCION_DESCARTADA_ON_IMPLEMENTACION_MODELO foreign key (IMPLEMENTACION_MODELO_ID) references IMPLEMENTACION_MODELO(ID)^
create index IDX_TEST1_SECCION_DESCARTADA_ON_SECCION on TEST1_SECCION_DESCARTADA (SECCION_ID)^
create index IDX_TEST1_SECCION_DESCARTADA_ON_IMPLEMENTACION_MODELO on TEST1_SECCION_DESCARTADA (IMPLEMENTACION_MODELO_ID)^
-- end TEST1_SECCION_DESCARTADA
-- begin INCREMENTO
alter table INCREMENTO add constraint FK_INCREMENTO_ON_CONCEPTO_RECIBO_ATRASOS foreign key (CONCEPTO_RECIBO_ATRASOS_ID) references CONCEPTO_RECIBO(ID)^
alter table INCREMENTO add constraint FK_INCREMENTO_ON_TIPO_COEFICIENTE foreign key (TIPO_COEFICIENTE_ID) references TEST1_TIPO_COEFICIENTE(ID)^
alter table INCREMENTO add constraint FK_INCREMENTO_ON_CONCEPTO foreign key (CONCEPTO_ID) references CONCEPTO(ID)^
alter table INCREMENTO add constraint FK_INCREMENTO_ON_UBICACION foreign key (UBICACION_ID) references UBICACION(ID)^
create index IDX_INCREMENTO_ON_CONCEPTO_RECIBO_ATRASOS on INCREMENTO (CONCEPTO_RECIBO_ATRASOS_ID)^
create index IDX_INCREMENTO_ON_TIPO_COEFICIENTE on INCREMENTO (TIPO_COEFICIENTE_ID)^
create index IDX_INCREMENTO_ON_CONCEPTO on INCREMENTO (CONCEPTO_ID)^
create index IDX_INCREMENTO_ON_UBICACION on INCREMENTO (UBICACION_ID)^
-- end INCREMENTO
-- begin FIANZA
alter table FIANZA add constraint FK_FIANZA_ON_CONTRATO_INQUILINO foreign key (CONTRATO_INQUILINO_ID) references CONTRATO_INQUILINO(ID)^
alter table FIANZA add constraint FK_FIANZA_ON_ESCANEO_ARCHIVO_ADJUNTO foreign key (ESCANEO_ARCHIVO_ADJUNTO_ID) references ARCHIVO_ADJUNTO(ID)^
alter table FIANZA add constraint FK_FIANZA_ON_ESCANEO_SEGURO_ARCHIVO_ADJUNTO foreign key (ESCANEO_SEGURO_ARCHIVO_ADJUNTO_ID) references ARCHIVO_ADJUNTO(ID)^
alter table FIANZA add constraint FK_FIANZA_ON_ESCANEO_FIANZA foreign key (ESCANEO_FIANZA_ID) references ARCHIVO_ADJUNTO(ID)^
create index IDX_FIANZA_ON_CONTRATO_INQUILINO on FIANZA (CONTRATO_INQUILINO_ID)^
create index IDX_FIANZA_ON_ESCANEO_ARCHIVO_ADJUNTO on FIANZA (ESCANEO_ARCHIVO_ADJUNTO_ID)^
create index IDX_FIANZA_ON_ESCANEO_SEGURO_ARCHIVO_ADJUNTO on FIANZA (ESCANEO_SEGURO_ARCHIVO_ADJUNTO_ID)^
create index IDX_FIANZA_ON_ESCANEO_FIANZA on FIANZA (ESCANEO_FIANZA_ID)^
-- end FIANZA
-- begin CONCEPTO_RECIBO
alter table CONCEPTO_RECIBO add constraint FK_CONCEPTO_RECIBO_ON_CONCEPTO foreign key (CONCEPTO_ID) references CONCEPTO(ID)^
alter table CONCEPTO_RECIBO add constraint FK_CONCEPTO_RECIBO_ON_PROGRAMACION_RECIBO foreign key (PROGRAMACION_RECIBO_ID) references PROGRAMACION_RECIBO(ID)^
alter table CONCEPTO_RECIBO add constraint FK_CONCEPTO_RECIBO_ON_INCREMENTO foreign key (INCREMENTO_ID) references INCREMENTO(ID)^
create index IDX_CONCEPTO_RECIBO_ON_CONCEPTO on CONCEPTO_RECIBO (CONCEPTO_ID)^
create index IDX_CONCEPTO_RECIBO_ON_PROGRAMACION_RECIBO on CONCEPTO_RECIBO (PROGRAMACION_RECIBO_ID)^
create index IDX_CONCEPTO_RECIBO_ON_INCREMENTO on CONCEPTO_RECIBO (INCREMENTO_ID)^
-- end CONCEPTO_RECIBO
-- begin CLAUSULA
alter table CLAUSULA add constraint FK_CLAUSULA_ON_SECCION foreign key (SECCION_ID) references SECCION(ID)^
create index IDX_CLAUSULA_ON_SECCION on CLAUSULA (SECCION_ID)^
-- end CLAUSULA
-- begin SECCION
alter table SECCION add constraint FK_SECCION_ON_MODELO_CONTRATO foreign key (MODELO_CONTRATO_ID) references MODELO_CONTRATO(ID)^
create index IDX_SECCION_ON_MODELO_CONTRATO on SECCION (MODELO_CONTRATO_ID)^
-- end SECCION
-- begin PROGRAMACION_RECIBO
alter table PROGRAMACION_RECIBO add constraint FK_PROGRAMACION_RECIBO_ON_CONTRATO_INQUILINO foreign key (CONTRATO_INQUILINO_ID) references CONTRATO_INQUILINO(ID)^
alter table PROGRAMACION_RECIBO add constraint FK_PROGRAMACION_RECIBO_ON_CUENTA_BANCARIA_INQUILINO foreign key (CUENTA_BANCARIA_INQUILINO_ID) references CUENTA_BANCARIA(ID)^
alter table PROGRAMACION_RECIBO add constraint FK_PROGRAMACION_RECIBO_ON_DEFINICION_REMESA foreign key (DEFINICION_REMESA_ID) references DEFINICION_REMESA(ID)^
alter table PROGRAMACION_RECIBO add constraint FK_PROGRAMACION_RECIBO_ON_CUENTA_BANCARIA_PAGADOR foreign key (CUENTA_BANCARIA_PAGADOR_ID) references CUENTA_BANCARIA(ID)^
create index IDX_PROGRAMACION_RECIBO_ON_CONTRATO_INQUILINO on PROGRAMACION_RECIBO (CONTRATO_INQUILINO_ID)^
create index IDX_PROGRAMACION_RECIBO_ON_CUENTA_BANCARIA_INQUILINO on PROGRAMACION_RECIBO (CUENTA_BANCARIA_INQUILINO_ID)^
create index IDX_PROGRAMACION_RECIBO_ON_DEFINICION_REMESA on PROGRAMACION_RECIBO (DEFINICION_REMESA_ID)^
create index IDX_PROGRAMACION_RECIBO_ON_CUENTA_BANCARIA_PAGADOR on PROGRAMACION_RECIBO (CUENTA_BANCARIA_PAGADOR_ID)^
-- end PROGRAMACION_RECIBO
-- begin CONTRATO_INQUILINO
alter table CONTRATO_INQUILINO add constraint FK_CONTRATO_INQUILINO_ON_CICLO foreign key (CICLO_ID) references CICLO(ID)^
alter table CONTRATO_INQUILINO add constraint FK_CONTRATO_INQUILINO_ON_COLECCION_ARCHIVOS_ADJUNTOS foreign key (COLECCION_ARCHIVOS_ADJUNTOS_ID) references COLECCION_ARCHIVOS_ADJUNTOS(ID)^
alter table CONTRATO_INQUILINO add constraint FK_CONTRATO_INQUILINO_ON_PAGADOR foreign key (PAGADOR_ID) references PERSONA(ID)^
alter table CONTRATO_INQUILINO add constraint FK_CONTRATO_INQUILINO_ON_DEPARTAMENTO foreign key (DEPARTAMENTO_ID) references DEPARTAMENTO(ID)^
alter table CONTRATO_INQUILINO add constraint FK_CONTRATO_INQUILINO_ON_ESCANEO_CONTRATO foreign key (ESCANEO_CONTRATO_ID) references ARCHIVO_ADJUNTO(ID)^
alter table CONTRATO_INQUILINO add constraint FK_CONTRATO_INQUILINO_ON_IMPLEMENTACION_MODELO foreign key (IMPLEMENTACION_MODELO_ID) references IMPLEMENTACION_MODELO(ID)^
alter table CONTRATO_INQUILINO add constraint FK_CONTRATO_INQUILINO_ON_INQUILINO foreign key (INQUILINO_ID) references PERSONA(ID)^
alter table CONTRATO_INQUILINO add constraint FK_CONTRATO_INQUILINO_ON_REPRESENTANTE_ARRENDADOR foreign key (REPRESENTANTE_ARRENDADOR_ID) references PERSONA(ID)^
alter table CONTRATO_INQUILINO add constraint FK_CONTRATO_INQUILINO_ON_REPRESENTANTE_ARRENDATARIO foreign key (REPRESENTANTE_ARRENDATARIO_ID) references PERSONA(ID)^
alter table CONTRATO_INQUILINO add constraint FK_CONTRATO_INQUILINO_ON_COMERCIAL_OFERTAS foreign key (COMERCIAL_OFERTAS_ID) references COMERCIAL_OFERTAS(ID)^
alter table CONTRATO_INQUILINO add constraint FK_CONTRATO_INQUILINO_ON_OFERTA foreign key (OFERTA_ID) references OFERTA(ID)^
alter table CONTRATO_INQUILINO add constraint FK_CONTRATO_INQUILINO_ON_ARCHIVO_ADJUNTO_RENUNCIA foreign key (ARCHIVO_ADJUNTO_RENUNCIA_ID) references ARCHIVO_ADJUNTO(ID)^
alter table CONTRATO_INQUILINO add constraint FK_CONTRATO_INQUILINO_ON_CARPETA_DOCUMENTO_FOTOGRAFICO_FIRMA foreign key (CARPETA_DOCUMENTO_FOTOGRAFICO_FIRMA_ID) references CTA_DOCTOS_FOTOGRAFICOS(ID)^
create index IDX_CONTRATO_INQUILINO_ON_CICLO on CONTRATO_INQUILINO (CICLO_ID)^
create index IDX_CONTRATO_INQUILINO_ON_COLECCION_ARCHIVOS_ADJUNTOS on CONTRATO_INQUILINO (COLECCION_ARCHIVOS_ADJUNTOS_ID)^
create index IDX_CONTRATO_INQUILINO_ON_PAGADOR on CONTRATO_INQUILINO (PAGADOR_ID)^
create index IDX_CONTRATO_INQUILINO_ON_DEPARTAMENTO on CONTRATO_INQUILINO (DEPARTAMENTO_ID)^
create index IDX_CONTRATO_INQUILINO_ON_ESCANEO_CONTRATO on CONTRATO_INQUILINO (ESCANEO_CONTRATO_ID)^
create index IDX_CONTRATO_INQUILINO_ON_IMPLEMENTACION_MODELO on CONTRATO_INQUILINO (IMPLEMENTACION_MODELO_ID)^
create index IDX_CONTRATO_INQUILINO_ON_INQUILINO on CONTRATO_INQUILINO (INQUILINO_ID)^
create index IDX_CONTRATO_INQUILINO_ON_REPRESENTANTE_ARRENDADOR on CONTRATO_INQUILINO (REPRESENTANTE_ARRENDADOR_ID)^
create index IDX_CONTRATO_INQUILINO_ON_REPRESENTANTE_ARRENDATARIO on CONTRATO_INQUILINO (REPRESENTANTE_ARRENDATARIO_ID)^
create index IDX_CONTRATO_INQUILINO_ON_COMERCIAL_OFERTAS on CONTRATO_INQUILINO (COMERCIAL_OFERTAS_ID)^
create index IDX_CONTRATO_INQUILINO_ON_OFERTA on CONTRATO_INQUILINO (OFERTA_ID)^
create index IDX_CONTRATO_INQUILINO_ON_ARCHIVO_ADJUNTO_RENUNCIA on CONTRATO_INQUILINO (ARCHIVO_ADJUNTO_RENUNCIA_ID)^
create index IDX_CONTRATO_INQUILINO_ON_CARPETA_DOCUMENTO_FOTOGRAFICO_FIRMA on CONTRATO_INQUILINO (CARPETA_DOCUMENTO_FOTOGRAFICO_FIRMA_ID)^
-- end CONTRATO_INQUILINO
-- begin NOTIFICACION_RECIBO
alter table NOTIFICACION_RECIBO add constraint FK_NOTIFICACION_RECIBO_ON_PROGRAMACION_RECIBO foreign key (PROGRAMACION_RECIBO_ID) references PROGRAMACION_CONCEPTO_ADICIONAL(ID)^
alter table NOTIFICACION_RECIBO add constraint FK_NOTIFICACION_RECIBO_ON_CONCEPTO_RECIBO foreign key (CONCEPTO_RECIBO_ID) references CONCEPTO_RECIBO(ID)^
create index IDX_NOTIFICACION_RECIBO_ON_PROGRAMACION_RECIBO on NOTIFICACION_RECIBO (PROGRAMACION_RECIBO_ID)^
create index IDX_NOTIFICACION_RECIBO_ON_CONCEPTO_RECIBO on NOTIFICACION_RECIBO (CONCEPTO_RECIBO_ID)^
-- end NOTIFICACION_RECIBO
-- begin CONCEPTO_ADICIONAL_CONCEPTO_RECIBO
alter table CONCEPTO_ADICIONAL_CONCEPTO_RECIBO add constraint FK_CONCEPTO_ADICIONAL_CONCEPTO_RECIBO_ON_CA foreign key (CA_ID) references CONCEPTO_ADICIONAL(ID)^
alter table CONCEPTO_ADICIONAL_CONCEPTO_RECIBO add constraint FK_CONCEPTO_ADICIONAL_CONCEPTO_RECIBO_ON_CONCEPTO_RECIBO foreign key (CONCEPTO_RECIBO_ID) references CONCEPTO_RECIBO(ID)^
create index IDX_CONCEPTO_ADICIONAL_CONCEPTO_RECIBO_ON_CA on CONCEPTO_ADICIONAL_CONCEPTO_RECIBO (CA_ID)^
create index IDX_CONCEPTO_ADICIONAL_CONCEPTO_RECIBO_ON_CONCEPTO_RECIBO on CONCEPTO_ADICIONAL_CONCEPTO_RECIBO (CONCEPTO_RECIBO_ID)^
-- end CONCEPTO_ADICIONAL_CONCEPTO_RECIBO
-- begin COTITULAR_CONTRATO_INQUILINO
alter table COTITULAR_CONTRATO_INQUILINO add constraint FK_COTITULAR_CONTRATO_INQUILINO_ON_CONTRATO_INQUILINO foreign key (CONTRATO_INQUILINO_ID) references CONTRATO_INQUILINO(ID)^
alter table COTITULAR_CONTRATO_INQUILINO add constraint FK_COTITULAR_CONTRATO_INQUILINO_ON_COTITULAR foreign key (COTITULAR_ID) references PERSONA(ID)^
create index IDX_COTITULAR_CONTRATO_INQUILINO_ON_CONTRATO_INQUILINO on COTITULAR_CONTRATO_INQUILINO (CONTRATO_INQUILINO_ID)^
create index IDX_COTITULAR_CONTRATO_INQUILINO_ON_COTITULAR on COTITULAR_CONTRATO_INQUILINO (COTITULAR_ID)^
-- end COTITULAR_CONTRATO_INQUILINO
-- begin TEST1_REPRESENTACION_LEGAL
alter table TEST1_REPRESENTACION_LEGAL add constraint FK_TEST1_REPRESENTACION_LEGAL_ON_PERSONA foreign key (PERSONA_ID) references PERSONA(ID)^
alter table TEST1_REPRESENTACION_LEGAL add constraint FK_TEST1_REPRESENTACION_LEGAL_ON_PERSONA_REPRESENTANTE foreign key (PERSONA_REPRESENTANTE_ID) references PERSONA(ID)^
create index IDX_TEST1_REPRESENTACION_LEGAL_ON_PERSONA on TEST1_REPRESENTACION_LEGAL (PERSONA_ID)^
create index IDX_TEST1_REPRESENTACION_LEGAL_ON_PERSONA_REPRESENTANTE on TEST1_REPRESENTACION_LEGAL (PERSONA_REPRESENTANTE_ID)^
-- end TEST1_REPRESENTACION_LEGAL
-- begin TEST1_COEFICIENTE
alter table TEST1_COEFICIENTE add constraint FK_TEST1_COEFICIENTE_ON_TIPO_COEFICIENTE foreign key (TIPO_COEFICIENTE_ID) references TEST1_TIPO_COEFICIENTE(ID)^
alter table TEST1_COEFICIENTE add constraint FK_TEST1_COEFICIENTE_ON_DEPARTAMENTO foreign key (DEPARTAMENTO_ID) references DEPARTAMENTO(ID)^
create index IDX_TEST1_COEFICIENTE_ON_TIPO_COEFICIENTE on TEST1_COEFICIENTE (TIPO_COEFICIENTE_ID)^
create index IDX_TEST1_COEFICIENTE_ON_DEPARTAMENTO on TEST1_COEFICIENTE (DEPARTAMENTO_ID)^
-- end TEST1_COEFICIENTE
-- begin ARCHIVO_ADJUNTO
alter table ARCHIVO_ADJUNTO add constraint FK_ARCHIVO_ADJUNTO_ON_COLECCION_ARCHIVOS_ADJUNTOS foreign key (COLECCION_ARCHIVOS_ADJUNTOS_ID) references COLECCION_ARCHIVOS_ADJUNTOS(ID)^
create index IDX_ARCHIVO_ADJUNTO_ON_COLECCION_ARCHIVOS_ADJUNTOS on ARCHIVO_ADJUNTO (COLECCION_ARCHIVOS_ADJUNTOS_ID)^
-- end ARCHIVO_ADJUNTO
-- begin IMPUTACION_DOCUMENTO_IMPUTABLE
alter table IMPUTACION_DOCUMENTO_IMPUTABLE add constraint FK_IMPUTACION_DOCUMENTO_IMPUTABLE_ON_VALIDACION_IMPUTACION foreign key (VALIDACION_IMPUTACION_ID) references VALIDACION(ID)^
alter table IMPUTACION_DOCUMENTO_IMPUTABLE add constraint FK_IMPUTACION_DOCUMENTO_IMPUTABLE_ON_DOCUMENTO_IMPUTABLE foreign key (DOCUMENTO_IMPUTABLE_ID) references DOCUMENTO_IMPUTABLE(ID)^
alter table IMPUTACION_DOCUMENTO_IMPUTABLE add constraint FK_IMPUTACION_DOCUMENTO_IMPUTABLE_ON_CICLO foreign key (CICLO_ID) references CICLO(ID)^
alter table IMPUTACION_DOCUMENTO_IMPUTABLE add constraint FK_IMPUTACION_DOCUMENTO_IMPUTABLE_ON_EVENTO foreign key (EVENTO_ID) references EVENTO(ID)^
create index IDX_IMPUTACION_DOCUMENTO_IMPUTABLE_ON_VALIDACION_IMPUTACION on IMPUTACION_DOCUMENTO_IMPUTABLE (VALIDACION_IMPUTACION_ID)^
create index IDX_IMPUTACION_DOCUMENTO_IMPUTABLE_ON_DOCUMENTO_IMPUTABLE on IMPUTACION_DOCUMENTO_IMPUTABLE (DOCUMENTO_IMPUTABLE_ID)^
create index IDX_IMPUTACION_DOCUMENTO_IMPUTABLE_ON_CICLO on IMPUTACION_DOCUMENTO_IMPUTABLE (CICLO_ID)^
create index IDX_IMPUTACION_DOCUMENTO_IMPUTABLE_ON_EVENTO on IMPUTACION_DOCUMENTO_IMPUTABLE (EVENTO_ID)^
-- end IMPUTACION_DOCUMENTO_IMPUTABLE
-- begin NOTA_INTERVENCION
alter table NOTA_INTERVENCION add constraint FK_NOTA_INTERVENCION_ON_ORDEN_TRABAJO foreign key (ORDEN_TRABAJO_ID) references ORDEN_TRABAJO(ID)^
create index IDX_NOTA_INTERVENCION_ON_ORDEN_TRABAJO on NOTA_INTERVENCION (ORDEN_TRABAJO_ID)^
-- end NOTA_INTERVENCION
-- begin CEDULA_HABITABILIDAD
alter table CEDULA_HABITABILIDAD add constraint FK_CEDULA_HABITABILIDAD_ON_DEPARTAMENTO foreign key (DEPARTAMENTO_ID) references DEPARTAMENTO(ID)^
alter table CEDULA_HABITABILIDAD add constraint FK_CEDULA_HABITABILIDAD_ON_ESCANEO_CEDULA foreign key (ESCANEO_CEDULA_ID) references ARCHIVO_ADJUNTO(ID)^
create index IDX_CEDULA_HABITABILIDAD_ON_DEPARTAMENTO on CEDULA_HABITABILIDAD (DEPARTAMENTO_ID)^
create index IDX_CEDULA_HABITABILIDAD_ON_ESCANEO_CEDULA on CEDULA_HABITABILIDAD (ESCANEO_CEDULA_ID)^
-- end CEDULA_HABITABILIDAD
-- begin PARAMETRO_VALOR_ANEXO
alter table PARAMETRO_VALOR_ANEXO add constraint FK_PARAMETRO_VALOR_ANEXO_ON_ANEXO foreign key (ANEXO_ID) references ANEXO(ID)^
create index IDX_PARAMETRO_VALOR_ANEXO_ON_ANEXO on PARAMETRO_VALOR_ANEXO (ANEXO_ID)^
-- end PARAMETRO_VALOR_ANEXO
-- begin TEST1_ORDEN_COBRO
alter table TEST1_ORDEN_COBRO add constraint FK_TEST1_ORDEN_COBRO_ON_REALIZACION_COBRO foreign key (REALIZACION_COBRO_ID) references TEST1_REALIZACION_COBRO(ID)^
alter table TEST1_ORDEN_COBRO add constraint FK_TEST1_ORDEN_COBRO_ON_RECIBO foreign key (RECIBO_ID) references RECIBO(ID)^
create index IDX_TEST1_ORDEN_COBRO_ON_REALIZACION_COBRO on TEST1_ORDEN_COBRO (REALIZACION_COBRO_ID)^
create index IDX_TEST1_ORDEN_COBRO_ON_RECIBO on TEST1_ORDEN_COBRO (RECIBO_ID)^
-- end TEST1_ORDEN_COBRO
-- begin SERIE
alter table SERIE add constraint FK_SERIE_ON_MASTER_SERIE foreign key (MASTER_SERIE_ID) references SERIE(ID)^
create index IDX_SERIE_ON_MASTER_SERIE on SERIE (MASTER_SERIE_ID)^
-- end SERIE
-- begin ORDEN_TRABAJO
alter table ORDEN_TRABAJO add constraint FK_ORDEN_TRABAJO_ON_ENTRADA foreign key (ENTRADA_ID) references ENTRADA(ID)^
alter table ORDEN_TRABAJO add constraint FK_ORDEN_TRABAJO_ON_CARPETA_DOCUMENTOS_FOTOGRAFICOS foreign key (CARPETA_DOCUMENTOS_FOTOGRAFICOS_ID) references CTA_DOCTOS_FOTOGRAFICOS(ID)^
alter table ORDEN_TRABAJO add constraint FK_ORDEN_TRABAJO_ON_ADMINISTRADOR foreign key (ADMINISTRADOR_ID) references SEC_USER(ID)^
create index IDX_ORDEN_TRABAJO_ON_ENTRADA on ORDEN_TRABAJO (ENTRADA_ID)^
create index IDX_ORDEN_TRABAJO_ON_CARPETA_DOCUMENTOS_FOTOGRAFICOS on ORDEN_TRABAJO (CARPETA_DOCUMENTOS_FOTOGRAFICOS_ID)^
create index IDX_ORDEN_TRABAJO_ON_ADMINISTRADOR on ORDEN_TRABAJO (ADMINISTRADOR_ID)^
-- end ORDEN_TRABAJO
-- begin REMESA
alter table REMESA add constraint FK_REMESA_ON_DEFINICION_REMESA foreign key (DEFINICION_REMESA_ID) references DEFINICION_REMESA(ID)^
create index IDX_REMESA_ON_DEFINICION_REMESA on REMESA (DEFINICION_REMESA_ID)^
-- end REMESA
-- begin ORDENANTE_REMESA
alter table ORDENANTE_REMESA add constraint FK_ORDENANTE_REMESA_ON_DEFINICION_REMESA foreign key (DEFINICION_REMESA_ID) references DEFINICION_REMESA(ID)^
alter table ORDENANTE_REMESA add constraint FK_ORDENANTE_REMESA_ON_REMESA foreign key (REMESA_ID) references REMESA(ID)^
create index IDX_ORDENANTE_REMESA_ON_DEFINICION_REMESA on ORDENANTE_REMESA (DEFINICION_REMESA_ID)^
create index IDX_ORDENANTE_REMESA_ON_REMESA on ORDENANTE_REMESA (REMESA_ID)^
-- end ORDENANTE_REMESA
-- begin CICLO
alter table CICLO add constraint FK_CICLO_ON_COLECCION_ADJUNTOS foreign key (COLECCION_ADJUNTOS_ID) references COLECCION_ARCHIVOS_ADJUNTOS(ID)^
alter table CICLO add constraint FK_CICLO_ON_DEPARTAMENTO foreign key (DEPARTAMENTO_ID) references DEPARTAMENTO(ID)^
alter table CICLO add constraint FK_CICLO_ON_CONTRATO_INQUILINO foreign key (CONTRATO_INQUILINO_ID) references CONTRATO_INQUILINO(ID)^
create index IDX_CICLO_ON_COLECCION_ADJUNTOS on CICLO (COLECCION_ADJUNTOS_ID)^
create index IDX_CICLO_ON_DEPARTAMENTO on CICLO (DEPARTAMENTO_ID)^
create index IDX_CICLO_ON_CONTRATO_INQUILINO on CICLO (CONTRATO_INQUILINO_ID)^
-- end CICLO
-- begin FOTO_DOCUMENTO_FOTOGRAFICO
alter table FOTO_DOCUMENTO_FOTOGRAFICO add constraint FK_FOTO_DOCUMENTO_FOTOGRAFICO_ON_CARPETA foreign key (CARPETA_ID) references CTA_DOCTOS_FOTOGRAFICOS(ID)^
alter table FOTO_DOCUMENTO_FOTOGRAFICO add constraint FK_FOTO_DOCUMENTO_FOTOGRAFICO_ON_FOTO_THUMBNAIL foreign key (FOTO_THUMBNAIL_ID) references TEST1_FOTO_THUMBNAIL(ID)^
create index IDX_FOTO_DOCUMENTO_FOTOGRAFICO_ON_CARPETA on FOTO_DOCUMENTO_FOTOGRAFICO (CARPETA_ID)^
create index IDX_FOTO_DOCUMENTO_FOTOGRAFICO_ON_FOTO_THUMBNAIL on FOTO_DOCUMENTO_FOTOGRAFICO (FOTO_THUMBNAIL_ID)^
-- end FOTO_DOCUMENTO_FOTOGRAFICO
-- begin PROGRAMACION_CONCEPTO_ADICIONAL
alter table PROGRAMACION_CONCEPTO_ADICIONAL add constraint FK_PROGRAMACION_CONCEPTO_ADICIONAL_ON_CONCEPTO_ADICIONAL foreign key (CONCEPTO_ADICIONAL_ID) references CONCEPTO_ADICIONAL(ID)^
alter table PROGRAMACION_CONCEPTO_ADICIONAL add constraint FK_PROGRAMACION_CONCEPTO_ADICIONAL_ON_PROVEEDOR foreign key (PROVEEDOR_ID) references PROVEEDOR(ID)^
alter table PROGRAMACION_CONCEPTO_ADICIONAL add constraint FK_PROGRAMACION_CONCEPTO_ADICIONAL_ON_PROGRAMACION_RECIBO foreign key (PROGRAMACION_RECIBO_ID) references PROGRAMACION_RECIBO(ID)^
create index IDX_PROGRAMACION_CONCEPTO_ADICIONAL_ON_CONCEPTO_ADICIONAL on PROGRAMACION_CONCEPTO_ADICIONAL (CONCEPTO_ADICIONAL_ID)^
create index IDX_PROGRAMACION_CONCEPTO_ADICIONAL_ON_PROVEEDOR on PROGRAMACION_CONCEPTO_ADICIONAL (PROVEEDOR_ID)^
create index IDX_PROGRAMACION_CONCEPTO_ADICIONAL_ON_PROGRAMACION_RECIBO on PROGRAMACION_CONCEPTO_ADICIONAL (PROGRAMACION_RECIBO_ID)^
-- end PROGRAMACION_CONCEPTO_ADICIONAL
-- begin EVENTO
alter table EVENTO add constraint FK_EVENTO_ON_CICLO foreign key (CICLO_ID) references CICLO(ID)^
create index IDX_EVENTO_ON_CICLO on EVENTO (CICLO_ID)^
-- end EVENTO
-- begin CTA_DOCTOS_FOTOGRAFICOS
alter table CTA_DOCTOS_FOTOGRAFICOS add constraint FK_CTA_DOCTOS_FOTOGRAFICOS_ON_CICLO foreign key (CICLO_ID) references CICLO(ID)^
alter table CTA_DOCTOS_FOTOGRAFICOS add constraint FK_CTA_DOCTOS_FOTOGRAFICOS_ON_EVENTO foreign key (EVENTO_ID) references EVENTO(ID)^
alter table CTA_DOCTOS_FOTOGRAFICOS add constraint FK_CTA_DOCTOS_FOTOGRAFICOS_ON_LIQUIDACION_EXTINCION foreign key (LIQUIDACION_EXTINCION_ID) references LIQUIDACION_EXTINCION(ID)^
create index IDX_CTA_DOCTOS_FOTOGRAFICOS_ON_CICLO on CTA_DOCTOS_FOTOGRAFICOS (CICLO_ID)^
create index IDX_CTA_DOCTOS_FOTOGRAFICOS_ON_EVENTO on CTA_DOCTOS_FOTOGRAFICOS (EVENTO_ID)^
create index IDX_CTA_DOCTOS_FOTOGRAFICOS_ON_LIQUIDACION_EXTINCION on CTA_DOCTOS_FOTOGRAFICOS (LIQUIDACION_EXTINCION_ID)^
-- end CTA_DOCTOS_FOTOGRAFICOS
-- begin UBICACION
alter table UBICACION add constraint FK_UBICACION_ON_DIRECCION foreign key (DIRECCION_ID) references DIRECCION(ID)^
alter table UBICACION add constraint FK_UBICACION_ON_PROPIETARIO foreign key (PROPIETARIO_ID) references PROPIETARIO(ID)^
alter table UBICACION add constraint FK_UBICACION_ON_COLECCION_ARCHIVOS_ADJUNTOS foreign key (COLECCION_ARCHIVOS_ADJUNTOS_ID) references COLECCION_ARCHIVOS_ADJUNTOS(ID)^
alter table UBICACION add constraint FK_UBICACION_ON_FOTO_FACHADA foreign key (FOTO_FACHADA_ID) references ARCHIVO_ADJUNTO(ID)^
create index IDX_UBICACION_ON_DIRECCION on UBICACION (DIRECCION_ID)^
create index IDX_UBICACION_ON_PROPIETARIO on UBICACION (PROPIETARIO_ID)^
create index IDX_UBICACION_ON_COLECCION_ARCHIVOS_ADJUNTOS on UBICACION (COLECCION_ARCHIVOS_ADJUNTOS_ID)^
create index IDX_UBICACION_ON_FOTO_FACHADA on UBICACION (FOTO_FACHADA_ID)^
-- end UBICACION
-- begin ASIGNACION_TAREA
alter table ASIGNACION_TAREA add constraint FK_ASIGNACION_TAREA_ON_PROVEEDOR foreign key (PROVEEDOR_ID) references PROVEEDOR(ID)^
alter table ASIGNACION_TAREA add constraint FK_ASIGNACION_TAREA_ON_ORDEN_TRABAJO foreign key (ORDEN_TRABAJO_ID) references ORDEN_TRABAJO(ID)^
create index IDX_ASIGNACION_TAREA_ON_PROVEEDOR on ASIGNACION_TAREA (PROVEEDOR_ID)^
create index IDX_ASIGNACION_TAREA_ON_ORDEN_TRABAJO on ASIGNACION_TAREA (ORDEN_TRABAJO_ID)^
-- end ASIGNACION_TAREA
-- begin RECIBO
alter table RECIBO add constraint FK_RECIBO_ON_PROGRAMACION_RECIBO foreign key (PROGRAMACION_RECIBO_ID) references PROGRAMACION_RECIBO(ID)^
alter table RECIBO add constraint FK_RECIBO_ON_ORDENANTE_REMESA foreign key (ORDENANTE_REMESA_ID) references ORDENANTE_REMESA(ID)^
alter table RECIBO add constraint FK_RECIBO_ON_SERIE foreign key (SERIE_ID) references SERIE(ID)^
alter table RECIBO add constraint FK_RECIBO_ON_UTILITARIO_CONTRATO_INQUILINO foreign key (UTILITARIO_CONTRATO_INQUILINO_ID) references CONTRATO_INQUILINO(ID)^
alter table RECIBO add constraint FK_RECIBO_ON_UTILITARIO_INQUILINO foreign key (UTILITARIO_INQUILINO_ID) references PERSONA(ID)^
create index IDX_RECIBO_ON_PROGRAMACION_RECIBO on RECIBO (PROGRAMACION_RECIBO_ID)^
create index IDX_RECIBO_ON_ORDENANTE_REMESA on RECIBO (ORDENANTE_REMESA_ID)^
create index IDX_RECIBO_ON_SERIE on RECIBO (SERIE_ID)^
create index IDX_RECIBO_ON_UTILITARIO_CONTRATO_INQUILINO on RECIBO (UTILITARIO_CONTRATO_INQUILINO_ID)^
create index IDX_RECIBO_ON_UTILITARIO_INQUILINO on RECIBO (UTILITARIO_INQUILINO_ID)^
-- end RECIBO
-- begin RECIBO_COBRADO
alter table RECIBO_COBRADO add constraint FK_RECIBO_COBRADO_ON_RECIBO foreign key (RECIBO_ID) references RECIBO(ID)^
create index IDX_RECIBO_COBRADO_ON_RECIBO on RECIBO_COBRADO (RECIBO_ID)^
-- end RECIBO_COBRADO
-- begin LIQUIDACION_EXTINCION
alter table LIQUIDACION_EXTINCION add constraint FK_LIQUIDACION_EXTINCION_ON_ESCANEO_LIQUIDACION foreign key (ESCANEO_LIQUIDACION_ID) references ARCHIVO_ADJUNTO(ID)^
alter table LIQUIDACION_EXTINCION add constraint FK_LIQUIDACION_EXTINCION_ON_CONTRATO_INQUILINO foreign key (CONTRATO_INQUILINO_ID) references CONTRATO_INQUILINO(ID)^
alter table LIQUIDACION_EXTINCION add constraint FK_LIQUIDACION_EXTINCION_ON_RETENCION_CDF foreign key (RETENCION_CDF_ID) references CTA_DOCTOS_FOTOGRAFICOS(ID)^
create index IDX_LIQUIDACION_EXTINCION_ON_ESCANEO_LIQUIDACION on LIQUIDACION_EXTINCION (ESCANEO_LIQUIDACION_ID)^
create index IDX_LIQUIDACION_EXTINCION_ON_CONTRATO_INQUILINO on LIQUIDACION_EXTINCION (CONTRATO_INQUILINO_ID)^
create index IDX_LIQUIDACION_EXTINCION_ON_RETENCION_CDF on LIQUIDACION_EXTINCION (RETENCION_CDF_ID)^
-- end LIQUIDACION_EXTINCION
-- begin COMERCIAL_OFERTAS
alter table COMERCIAL_OFERTAS add constraint FK_COMERCIAL_OFERTAS_ON_PROVEEDOR foreign key (PROVEEDOR_ID) references PROVEEDOR(ID)^
alter table COMERCIAL_OFERTAS add constraint FK_COMERCIAL_OFERTAS_ON_ESCANEO_ACEPTACION foreign key (ESCANEO_ACEPTACION_ID) references ARCHIVO_ADJUNTO(ID)^
create index IDX_COMERCIAL_OFERTAS_ON_PROVEEDOR on COMERCIAL_OFERTAS (PROVEEDOR_ID)^
create index IDX_COMERCIAL_OFERTAS_ON_ESCANEO_ACEPTACION on COMERCIAL_OFERTAS (ESCANEO_ACEPTACION_ID)^
-- end COMERCIAL_OFERTAS
-- begin ORDEN_PAGO
alter table ORDEN_PAGO add constraint FK_ORDEN_PAGO_ON_EMISOR_PERSONA foreign key (EMISOR_PERSONA_ID) references PERSONA(ID)^
alter table ORDEN_PAGO add constraint FK_ORDEN_PAGO_ON_BENEFICIARIO_PERSONA foreign key (BENEFICIARIO_PERSONA_ID) references PERSONA(ID)^
alter table ORDEN_PAGO add constraint FK_ORDEN_PAGO_ON_REALIZACION_PAGO foreign key (REALIZACION_PAGO_ID) references REALIZACION_PAGO(ID)^
alter table ORDEN_PAGO add constraint FK_ORDEN_PAGO_ON_CONTRATO_INQUILINO foreign key (CONTRATO_INQUILINO_ID) references CONTRATO_INQUILINO(ID)^
alter table ORDEN_PAGO add constraint FK_ORDEN_PAGO_ON_FACTURA_PROVEEDOR foreign key (FACTURA_PROVEEDOR_ID) references DOCUMENTO_IMPUTABLE(ID)^
alter table ORDEN_PAGO add constraint FK_ORDEN_PAGO_ON_PROVEEDOR_AB foreign key (PROVEEDOR_AB_ID) references PROVEEDOR(ID)^
alter table ORDEN_PAGO add constraint FK_ORDEN_PAGO_ON_FACTURA_PROVEEDOR_AB foreign key (FACTURA_PROVEEDOR_AB_ID) references DOCUMENTO_IMPUTABLE(ID)^
alter table ORDEN_PAGO add constraint FK_ORDEN_PAGO_ON_PROVEEDOR foreign key (PROVEEDOR_ID) references PROVEEDOR(ID)^
create index IDX_ORDEN_PAGO_ON_EMISOR_PERSONA on ORDEN_PAGO (EMISOR_PERSONA_ID)^
create index IDX_ORDEN_PAGO_ON_BENEFICIARIO_PERSONA on ORDEN_PAGO (BENEFICIARIO_PERSONA_ID)^
create index IDX_ORDEN_PAGO_ON_REALIZACION_PAGO on ORDEN_PAGO (REALIZACION_PAGO_ID)^
create index IDX_ORDEN_PAGO_ON_CONTRATO_INQUILINO on ORDEN_PAGO (CONTRATO_INQUILINO_ID)^
create index IDX_ORDEN_PAGO_ON_FACTURA_PROVEEDOR on ORDEN_PAGO (FACTURA_PROVEEDOR_ID)^
create index IDX_ORDEN_PAGO_ON_PROVEEDOR_AB on ORDEN_PAGO (PROVEEDOR_AB_ID)^
create index IDX_ORDEN_PAGO_ON_FACTURA_PROVEEDOR_AB on ORDEN_PAGO (FACTURA_PROVEEDOR_AB_ID)^
create index IDX_ORDEN_PAGO_ON_PROVEEDOR on ORDEN_PAGO (PROVEEDOR_ID)^
-- end ORDEN_PAGO
-- begin TEST1_UBICACION_COEFICIENTE
alter table TEST1_UBICACION_COEFICIENTE add constraint FK_TEST1_UBICACION_COEFICIENTE_ON_UBICACION foreign key (UBICACION_ID) references UBICACION(ID)^
alter table TEST1_UBICACION_COEFICIENTE add constraint FK_TEST1_UBICACION_COEFICIENTE_ON_TIPO_COEFICIENTE foreign key (TIPO_COEFICIENTE_ID) references TEST1_TIPO_COEFICIENTE(ID)^
create index IDX_TEST1_UBICACION_COEFICIENTE_ON_UBICACION on TEST1_UBICACION_COEFICIENTE (UBICACION_ID)^
create index IDX_TEST1_UBICACION_COEFICIENTE_ON_TIPO_COEFICIENTE on TEST1_UBICACION_COEFICIENTE (TIPO_COEFICIENTE_ID)^
-- end TEST1_UBICACION_COEFICIENTE
-- begin TEST1_REGISTRO_PRESENCIAL
alter table TEST1_REGISTRO_PRESENCIAL add constraint FK_TEST1_REGISTRO_PRESENCIAL_ON_USUARIO foreign key (USUARIO_ID) references SEC_USER(ID)^
create index IDX_TEST1_REGISTRO_PRESENCIAL_ON_USUARIO on TEST1_REGISTRO_PRESENCIAL (USUARIO_ID)^
-- end TEST1_REGISTRO_PRESENCIAL
-- begin VALIDACION
alter table VALIDACION add constraint FK_VALIDACION_ON_PROPIETARIO foreign key (PROPIETARIO_ID) references PROPIETARIO(ID)^
create index IDX_VALIDACION_ON_PROPIETARIO on VALIDACION (PROPIETARIO_ID)^
-- end VALIDACION
-- begin DEFINICION_REMESA
alter table DEFINICION_REMESA add constraint FK_DEFINICION_REMESA_ON_PROPIETARIO foreign key (PROPIETARIO_ID) references PROPIETARIO(ID)^
alter table DEFINICION_REMESA add constraint FK_DEFINICION_REMESA_ON_CUENTA_BANCARIA foreign key (CUENTA_BANCARIA_ID) references CUENTA_BANCARIA(ID)^
alter table DEFINICION_REMESA add constraint FK_DEFINICION_REMESA_ON_DELEGADO foreign key (DELEGADO_ID) references PERSONA(ID)^
create index IDX_DEFINICION_REMESA_ON_PROPIETARIO on DEFINICION_REMESA (PROPIETARIO_ID)^
create index IDX_DEFINICION_REMESA_ON_CUENTA_BANCARIA on DEFINICION_REMESA (CUENTA_BANCARIA_ID)^
create index IDX_DEFINICION_REMESA_ON_DELEGADO on DEFINICION_REMESA (DELEGADO_ID)^
-- end DEFINICION_REMESA
-- begin TEST1_DOCUMENTACION_INQUILINO
alter table TEST1_DOCUMENTACION_INQUILINO add constraint FK_TEST1_DOCUMENTACION_INQUILINO_ON_COLECCION_ARCHIVOS_ADJUNTOS foreign key (COLECCION_ARCHIVOS_ADJUNTOS_ID) references COLECCION_ARCHIVOS_ADJUNTOS(ID)^
alter table TEST1_DOCUMENTACION_INQUILINO add constraint FK_TEST1_DOCUMENTACION_INQUILINO_ON_CONTRATO_INQUILINO foreign key (CONTRATO_INQUILINO_ID) references CONTRATO_INQUILINO(ID)^
create index IDX_TEST1_DOCUMENTACION_INQUILINO_ON_COLECCION_ARCHIVOS_ADJUNTOS on TEST1_DOCUMENTACION_INQUILINO (COLECCION_ARCHIVOS_ADJUNTOS_ID)^
create index IDX_TEST1_DOCUMENTACION_INQUILINO_ON_CONTRATO_INQUILINO on TEST1_DOCUMENTACION_INQUILINO (CONTRATO_INQUILINO_ID)^
-- end TEST1_DOCUMENTACION_INQUILINO
-- begin ENTRADA
alter table ENTRADA add constraint FK_ENTRADA_ON_CICLO foreign key (CICLO_ID) references CICLO(ID)^
alter table ENTRADA add constraint FK_ENTRADA_ON_EVENTO foreign key (EVENTO_ID) references EVENTO(ID)^
create index IDX_ENTRADA_ON_CICLO on ENTRADA (CICLO_ID)^
create index IDX_ENTRADA_ON_EVENTO on ENTRADA (EVENTO_ID)^
-- end ENTRADA
-- begin OVERRIDE_CLAUSULA
alter table OVERRIDE_CLAUSULA add constraint FK_OVERRIDE_CLAUSULA_ON_CLAUSULA foreign key (CLAUSULA_ID) references CLAUSULA(ID)^
alter table OVERRIDE_CLAUSULA add constraint FK_OVERRIDE_CLAUSULA_ON_VERSION_APLICADA foreign key (VERSION_APLICADA_ID) references VERSION_CLAUSULA(ID)^
alter table OVERRIDE_CLAUSULA add constraint FK_OVERRIDE_CLAUSULA_ON_IMPLEMENTACION_MODELO foreign key (IMPLEMENTACION_MODELO_ID) references IMPLEMENTACION_MODELO(ID)^
create index IDX_OVERRIDE_CLAUSULA_ON_CLAUSULA on OVERRIDE_CLAUSULA (CLAUSULA_ID)^
create index IDX_OVERRIDE_CLAUSULA_ON_VERSION_APLICADA on OVERRIDE_CLAUSULA (VERSION_APLICADA_ID)^
create index IDX_OVERRIDE_CLAUSULA_ON_IMPLEMENTACION_MODELO on OVERRIDE_CLAUSULA (IMPLEMENTACION_MODELO_ID)^
-- end OVERRIDE_CLAUSULA
-- begin PROPIETARIO
alter table PROPIETARIO add constraint FK_PROPIETARIO_ON_PERSONA foreign key (PERSONA_ID) references PERSONA(ID)^
alter table PROPIETARIO add constraint FK_PROPIETARIO_ON_CABECERA_DOCUMENTOS_ARCHIVO_ADJUNTO foreign key (CABECERA_DOCUMENTOS_ARCHIVO_ADJUNTO_ID) references ARCHIVO_ADJUNTO(ID)^
alter table PROPIETARIO add constraint FK_PROPIETARIO_ON_CUENTA_BANCARIA foreign key (CUENTA_BANCARIA_ID) references CUENTA_BANCARIA(ID)^
create index IDX_PROPIETARIO_ON_PERSONA on PROPIETARIO (PERSONA_ID)^
create index IDX_PROPIETARIO_ON_CABECERA_DOCUMENTOS_ARCHIVO_ADJUNTO on PROPIETARIO (CABECERA_DOCUMENTOS_ARCHIVO_ADJUNTO_ID)^
create index IDX_PROPIETARIO_ON_CUENTA_BANCARIA on PROPIETARIO (CUENTA_BANCARIA_ID)^
-- end PROPIETARIO
-- begin REALIZACION_PAGO
alter table REALIZACION_PAGO add constraint FK_REALIZACION_PAGO_ON_CUENTA_BANCARIA foreign key (CUENTA_BANCARIA_ID) references CUENTA_BANCARIA(ID)^
create index IDX_REALIZACION_PAGO_ON_CUENTA_BANCARIA on REALIZACION_PAGO (CUENTA_BANCARIA_ID)^
-- end REALIZACION_PAGO
-- begin COMP_OP_PROVEEDOR
alter table COMP_OP_PROVEEDOR add constraint FK_COMP_OP_PROVEEDOR_ON_OP_PROVEEDOR foreign key (OP_PROVEEDOR_ID) references ORDEN_PAGO(ID)^
alter table COMP_OP_PROVEEDOR add constraint FK_COMP_OP_PROVEEDOR_ON_ORDEN_PAGO_ABONO foreign key (ORDEN_PAGO_ABONO_ID) references ORDEN_PAGO(ID)^
alter table COMP_OP_PROVEEDOR add constraint FK_COMP_OP_PROVEEDOR_ON_ORDEN_PAGO_FACTURA_PROVEEDOR foreign key (ORDEN_PAGO_FACTURA_PROVEEDOR_ID) references ORDEN_PAGO(ID)^
create index IDX_COMP_OP_PROVEEDOR_ON_OP_PROVEEDOR on COMP_OP_PROVEEDOR (OP_PROVEEDOR_ID)^
create index IDX_COMP_OP_PROVEEDOR_ON_ORDEN_PAGO_ABONO on COMP_OP_PROVEEDOR (ORDEN_PAGO_ABONO_ID)^
create index IDX_COMP_OP_PROVEEDOR_ON_ORDEN_PAGO_FACTURA_PROVEEDOR on COMP_OP_PROVEEDOR (ORDEN_PAGO_FACTURA_PROVEEDOR_ID)^
-- end COMP_OP_PROVEEDOR
-- begin TEST1_REGISTRO_INDICE_REFERENCIA
alter table TEST1_REGISTRO_INDICE_REFERENCIA add constraint FK_TEST1_REGISTRO_INDICE_REFERENCIA_ON_REALIZADO_POR_PERSONA foreign key (REALIZADO_POR_PERSONA_ID) references PERSONA(ID)^
create index IDX_TEST1_REGISTRO_INDICE_REFERENCIA_ON_REALIZADO_POR_PERSONA on TEST1_REGISTRO_INDICE_REFERENCIA (REALIZADO_POR_PERSONA_ID)^
-- end TEST1_REGISTRO_INDICE_REFERENCIA
-- begin CERTIFICADO_CALIFICACION_ENERGETICA
alter table CERTIFICADO_CALIFICACION_ENERGETICA add constraint FK_CERTIFICADO_CALIFICACION_ENERGETICA_ON_ARCHIVO_ADJUNTO foreign key (ARCHIVO_ADJUNTO_ID) references ARCHIVO_ADJUNTO(ID)^
alter table CERTIFICADO_CALIFICACION_ENERGETICA add constraint FK_CERTIFICADO_CALIFICACION_ENERGETICA_ON_DEPARTAMENTO foreign key (DEPARTAMENTO_ID) references DEPARTAMENTO(ID)^
create index IDX_CERTIFICADO_CALIFICACION_ENERGETICA_ON_ARCHIVO_ADJUNTO on CERTIFICADO_CALIFICACION_ENERGETICA (ARCHIVO_ADJUNTO_ID)^
create index IDX_CERTIFICADO_CALIFICACION_ENERGETICA_ON_DEPARTAMENTO on CERTIFICADO_CALIFICACION_ENERGETICA (DEPARTAMENTO_ID)^
-- end CERTIFICADO_CALIFICACION_ENERGETICA
-- begin TEST1_REALIZACION_COBRO
alter table TEST1_REALIZACION_COBRO add constraint FK_TEST1_REALIZACION_COBRO_ON_CUENTA_BANCARIA foreign key (CUENTA_BANCARIA_ID) references CUENTA_BANCARIA(ID)^
create index IDX_TEST1_REALIZACION_COBRO_ON_CUENTA_BANCARIA on TEST1_REALIZACION_COBRO (CUENTA_BANCARIA_ID)^
-- end TEST1_REALIZACION_COBRO
-- begin TEST1_RESERVA
alter table TEST1_RESERVA add constraint FK_TEST1_RESERVA_ON_COMERCIAL foreign key (COMERCIAL_ID) references COMERCIAL_OFERTAS(ID)^
alter table TEST1_RESERVA add constraint FK_TEST1_RESERVA_ON_OFERTA foreign key (OFERTA_ID) references OFERTA(ID)^
create index IDX_TEST1_RESERVA_ON_COMERCIAL on TEST1_RESERVA (COMERCIAL_ID)^
create index IDX_TEST1_RESERVA_ON_OFERTA on TEST1_RESERVA (OFERTA_ID)^
-- end TEST1_RESERVA
-- begin OFERTA
alter table OFERTA add constraint FK_OFERTA_ON_DEPARTAMENTO foreign key (DEPARTAMENTO_ID) references DEPARTAMENTO(ID)^
alter table OFERTA add constraint FK_OFERTA_ON_COMERCIAL_ALQUILER foreign key (COMERCIAL_ALQUILER_ID) references COMERCIAL_OFERTAS(ID)^
create index IDX_OFERTA_ON_DEPARTAMENTO on OFERTA (DEPARTAMENTO_ID)^
create index IDX_OFERTA_ON_COMERCIAL_ALQUILER on OFERTA (COMERCIAL_ALQUILER_ID)^
-- end OFERTA
