alter table DOCUMENTO_IMPUTABLE add column SUMINISTRO_PERIODO_DESDE date ;
alter table DOCUMENTO_IMPUTABLE add column SUMINISTRO_INFO_PUNTO_SUMINISTRO varchar(255) ;
alter table DOCUMENTO_IMPUTABLE add column SUMINISTRO_PERIODO_HASTA date ;
