alter table TEST1_DISPOSITIVO add constraint FK_TEST1_DISPOSITIVO_ON_DEPARTAMENTO foreign key (DEPARTAMENTO_ID) references DEPARTAMENTO(ID);
create index IDX_TEST1_DISPOSITIVO_ON_DEPARTAMENTO on TEST1_DISPOSITIVO (DEPARTAMENTO_ID);
