alter table TEST1_PUNTO_SUMINISTRO add constraint FK_TEST1_PUNTO_SUMINISTRO_ON_PROVEEDOR foreign key (PROVEEDOR_ID) references PROVEEDOR(ID);
create index IDX_TEST1_PUNTO_SUMINISTRO_ON_PROVEEDOR on TEST1_PUNTO_SUMINISTRO (PROVEEDOR_ID);
