alter table TEST1_PARAMETRO_VALOR_ANEXO add constraint FK_TEST1_PARAMETRO_VALOR_ANEXO_ON_ANEXO foreign key (ANEXO_ID) references ANEXO(ID);
create index IDX_TEST1_PARAMETRO_VALOR_ANEXO_ON_ANEXO on TEST1_PARAMETRO_VALOR_ANEXO (ANEXO_ID);
