alter table TEST1_PROVEEDOR add constraint FK_TEST1_PROVEEDOR_ON_CUENTA_BANCARIA foreign key (CUENTA_BANCARIA_ID) references TEST1_CUENTA_BANCARIA(ID);
create index IDX_TEST1_PROVEEDOR_ON_CUENTA_BANCARIA on TEST1_PROVEEDOR (CUENTA_BANCARIA_ID);
