alter table CONTRATO_INQUILINO add constraint FK_CONTRATO_INQUILINO_ON_OFERTA foreign key (OFERTA_ID) references OFERTA(ID);
create index IDX_CONTRATO_INQUILINO_ON_OFERTA on CONTRATO_INQUILINO (OFERTA_ID);
