alter table TEST1_CLAUSULA add constraint FK_TEST1_CLAUSULA_ON_SECCION foreign key (SECCION_ID) references TEST1_SECCION(ID);
create index IDX_TEST1_CLAUSULA_ON_SECCION on TEST1_CLAUSULA (SECCION_ID);
