alter table ORDEN_PAGO add constraint FK_ORDEN_PAGO_ON_REALIZACION_PAGO foreign key (REALIZACION_PAGO_ID) references TEST1_REALIZACION_PAGO(ID);
alter table ORDEN_PAGO add constraint FK_ORDEN_PAGO_ON_CONTRATO_INQUILINO foreign key (CONTRATO_INQUILINO_ID) references CONTRATO_INQUILINO(ID);
alter table ORDEN_PAGO add constraint FK_ORDEN_PAGO_ON_PROVEEDOR foreign key (PROVEEDOR_ID) references PROVEEDOR(ID);
create index IDX_ORDEN_PAGO_ON_REALIZACION_PAGO on ORDEN_PAGO (REALIZACION_PAGO_ID);
create index IDX_ORDEN_PAGO_ON_CONTRATO_INQUILINO on ORDEN_PAGO (CONTRATO_INQUILINO_ID);
create index IDX_ORDEN_PAGO_ON_PROVEEDOR on ORDEN_PAGO (PROVEEDOR_ID);
