alter table CONTRATO_INQUILINO add constraint FK_CONTRATO_INQUILINO_ON_INQUILINO foreign key (INQUILINO_ID) references PERSONA(ID);
create index IDX_CONTRATO_INQUILINO_ON_INQUILINO on CONTRATO_INQUILINO (INQUILINO_ID);
