alter table SECCION add constraint FK_SECCION_ON_MODELO_CONTRATO foreign key (MODELO_CONTRATO_ID) references MODELO_CONTRATO(ID);
create index IDX_SECCION_ON_MODELO_CONTRATO on SECCION (MODELO_CONTRATO_ID);
