alter table PROVEEDOR add constraint FK_PROVEEDOR_ON_PERSONA foreign key (PERSONA_ID) references PERSONA(ID);
alter table PROVEEDOR add constraint FK_PROVEEDOR_ON_COMERCIAL_OFERTAS foreign key (COMERCIAL_OFERTAS_ID) references COMERCIAL_OFERTAS(ID);
alter table PROVEEDOR add constraint FK_PROVEEDOR_ON_CUENTA_BANCARIA foreign key (CUENTA_BANCARIA_ID) references CUENTA_BANCARIA(ID);
create index IDX_PROVEEDOR_ON_PERSONA on PROVEEDOR (PERSONA_ID);
create index IDX_PROVEEDOR_ON_COMERCIAL_OFERTAS on PROVEEDOR (COMERCIAL_OFERTAS_ID);
create index IDX_PROVEEDOR_ON_CUENTA_BANCARIA on PROVEEDOR (CUENTA_BANCARIA_ID);
