alter table TEST1_CONCEPTO_RECIBO add constraint FK_TEST1_CONCEPTO_RECIBO_ON_CONCEPTO foreign key (CONCEPTO_ID) references TEST1_CONCEPTO(ID);
create index IDX_TEST1_CONCEPTO_RECIBO_ON_CONCEPTO on TEST1_CONCEPTO_RECIBO (CONCEPTO_ID);
