alter table TEST1_CUENTA_BANCARIA add constraint FK_TEST1_CUENTA_BANCARIA_ON_PERSONA foreign key (PERSONA_ID) references TEST1_PERSONA(ID);
create index IDX_TEST1_CUENTA_BANCARIA_ON_PERSONA on TEST1_CUENTA_BANCARIA (PERSONA_ID);
