alter table DOCUMENTO_IMPUTABLE add constraint FK_DOCUMENTO_IMPUTABLE_ON_PRESUPUESTO foreign key (PRESUPUESTO_ID) references DOCUMENTO_IMPUTABLE(ID);
create index IDX_DOCUMENTO_IMPUTABLE_ON_PRESUPUESTO on DOCUMENTO_IMPUTABLE (PRESUPUESTO_ID);
