alter table TEST1_PROVEEDOR add constraint FK_TEST1_PROVEEDOR_ON_PERSONA foreign key (PERSONA_ID) references TEST1_PERSONA(ID);
create index IDX_TEST1_PROVEEDOR_ON_PERSONA on TEST1_PROVEEDOR (PERSONA_ID);
