alter table ORDEN_TRABAJO add constraint FK_ORDEN_TRABAJO_ON_ADMINISTRADOR foreign key (ADMINISTRADOR_ID) references SEC_USER(ID);
create index IDX_ORDEN_TRABAJO_ON_ADMINISTRADOR on ORDEN_TRABAJO (ADMINISTRADOR_ID);
