alter table DEPARTAMENTO add constraint FK_DEPARTAMENTO_ON_COLECCION_ADJUNTOS foreign key (COLECCION_ADJUNTOS_ID) references COLECCION_ARCHIVOS_ADJUNTOS(ID);
alter table DEPARTAMENTO add constraint FK_DEPARTAMENTO_ON_PROPIETARIO foreign key (PROPIETARIO_ID) references PERSONA(ID);
alter table DEPARTAMENTO add constraint FK_DEPARTAMENTO_ON_UBICACION foreign key (UBICACION_ID) references UBICACION(ID);
alter table DEPARTAMENTO add constraint FK_DEPARTAMENTO_ON_PLANO_DEPARTAMENTO foreign key (PLANO_DEPARTAMENTO_ID) references ARCHIVO_ADJUNTO(ID);
create index IDX_DEPARTAMENTO_ON_COLECCION_ADJUNTOS on DEPARTAMENTO (COLECCION_ADJUNTOS_ID);
create index IDX_DEPARTAMENTO_ON_PROPIETARIO on DEPARTAMENTO (PROPIETARIO_ID);
create index IDX_DEPARTAMENTO_ON_UBICACION on DEPARTAMENTO (UBICACION_ID);
create index IDX_DEPARTAMENTO_ON_PLANO_DEPARTAMENTO on DEPARTAMENTO (PLANO_DEPARTAMENTO_ID);
