alter table TEST1_CICLO add constraint FK_TEST1_CICLO_ON_COLECCION_ADJUNTOS foreign key (COLECCION_ADJUNTOS_ID) references TEST1_COLECCION_ARCHIVOS_ADJUNTOS(ID);
alter table TEST1_CICLO add constraint FK_TEST1_CICLO_ON_DEPARTAMENTO foreign key (DEPARTAMENTO_ID) references TEST1_DEPARTAMENTO(ID);
alter table TEST1_CICLO add constraint FK_TEST1_CICLO_ON_CONTRATO_INQUILINO foreign key (CONTRATO_INQUILINO_ID) references TEST1_CONTRATO_INQUILINO(ID);
create index IDX_TEST1_CICLO_ON_COLECCION_ADJUNTOS on TEST1_CICLO (COLECCION_ADJUNTOS_ID);
create index IDX_TEST1_CICLO_ON_DEPARTAMENTO on TEST1_CICLO (DEPARTAMENTO_ID);
create index IDX_TEST1_CICLO_ON_CONTRATO_INQUILINO on TEST1_CICLO (CONTRATO_INQUILINO_ID);
