alter table TEST1_DEPARTAMENTO add constraint FK_TEST1_DEPARTAMENTO_ON_PROPIETARIO foreign key (PROPIETARIO_ID) references TEST1_PERSONA(ID);
create index IDX_TEST1_DEPARTAMENTO_ON_PROPIETARIO on TEST1_DEPARTAMENTO (PROPIETARIO_ID);
