alter table ANEXO add constraint FK_ANEXO_ON_PLANTILLA foreign key (PLANTILLA_ID) references PLANTILLA(ID);
alter table ANEXO add constraint FK_ANEXO_ON_CONTRATO_INQUILINO foreign key (CONTRATO_INQUILINO_ID) references CONTRATO_INQUILINO(ID);
create index IDX_ANEXO_ON_PLANTILLA on ANEXO (PLANTILLA_ID);
create index IDX_ANEXO_ON_CONTRATO_INQUILINO on ANEXO (CONTRATO_INQUILINO_ID);
