alter table CONTRATO_INQUILINO add constraint FK_CONTRATO_INQUILINO_ON_DEPARTAMENTO foreign key (DEPARTAMENTO_ID) references DEPARTAMENTO(ID);
create index IDX_CONTRATO_INQUILINO_ON_DEPARTAMENTO on CONTRATO_INQUILINO (DEPARTAMENTO_ID);
