alter table TEST1_DEPARTAMENTO add constraint FK_TEST1_DEPARTAMENTO_ON_UBICACION foreign key (UBICACION_ID) references TEST1_UBICACION(ID);
create index IDX_TEST1_DEPARTAMENTO_ON_UBICACION on TEST1_DEPARTAMENTO (UBICACION_ID);
