alter table TEST1_DIRECCION add constraint FK_TEST1_DIRECCION_ON_PERSONA foreign key (PERSONA_ID) references TEST1_PERSONA(ID);
create index IDX_TEST1_DIRECCION_ON_PERSONA on TEST1_DIRECCION (PERSONA_ID);
