alter table TEST1_ANEXO add constraint FK_TEST1_ANEXO_ON_PLANTILLA foreign key (PLANTILLA_ID) references TEST1_PLANTILLA(ID);
alter table TEST1_ANEXO add constraint FK_TEST1_ANEXO_ON_CONTRATO_INQUILINO foreign key (CONTRATO_INQUILINO_ID) references TEST1_CONTRATO_INQUILINO(ID);
create index IDX_TEST1_ANEXO_ON_PLANTILLA on TEST1_ANEXO (PLANTILLA_ID);
create index IDX_TEST1_ANEXO_ON_CONTRATO_INQUILINO on TEST1_ANEXO (CONTRATO_INQUILINO_ID);
