alter table SUBROGADOR add constraint FK_SUBROGADOR_ON_CONTRATO_INQUILINO foreign key (CONTRATO_INQUILINO_ID) references CONTRATO_INQUILINO(ID);
alter table SUBROGADOR add constraint FK_SUBROGADOR_ON_SUBROGADOR foreign key (SUBROGADOR_ID) references PERSONA(ID);
create index IDX_SUBROGADOR_ON_CONTRATO_INQUILINO on SUBROGADOR (CONTRATO_INQUILINO_ID);
create index IDX_SUBROGADOR_ON_SUBROGADOR on SUBROGADOR (SUBROGADOR_ID);
