alter table COMP_OP_PROVEEDOR add constraint FK_COMP_OP_PROVEEDOR_ON_OP_PROVEEDOR foreign key (OP_PROVEEDOR_ID) references ORDEN_PAGO(ID);
create index IDX_COMP_OP_PROVEEDOR_ON_OP_PROVEEDOR on COMP_OP_PROVEEDOR (OP_PROVEEDOR_ID);
