alter table VERSION_CLAUSULA add constraint FK_VERSION_CLAUSULA_ON_CLAUSULA foreign key (CLAUSULA_ID) references CLAUSULA(ID);
create index IDX_VERSION_CLAUSULA_ON_CLAUSULA on VERSION_CLAUSULA (CLAUSULA_ID);
