alter table TEST1_DIRECCION add constraint FK_TEST1_DIRECCION_ON_UBICACION foreign key (UBICACION_ID) references TEST1_UBICACION(ID);
create index IDX_TEST1_DIRECCION_ON_UBICACION on TEST1_DIRECCION (UBICACION_ID);
