alter table ASIGNACION_TAREA add constraint FK_ASIGNACION_TAREA_ON_PROVEEDOR foreign key (PROVEEDOR_ID) references PROVEEDOR(ID);
create index IDX_ASIGNACION_TAREA_ON_PROVEEDOR on ASIGNACION_TAREA (PROVEEDOR_ID);
