alter table FIANZA add constraint FK_FIANZA_ON_CONTRATO_INQUILINO foreign key (CONTRATO_INQUILINO_ID) references CONTRATO_INQUILINO(ID);
create index IDX_FIANZA_ON_CONTRATO_INQUILINO on FIANZA (CONTRATO_INQUILINO_ID);
