alter table DEFINICION_REMESA add constraint FK_DEFINICION_REMESA_ON_DELEGADO foreign key (DELEGADO_ID) references PERSONA(ID);
create index IDX_DEFINICION_REMESA_ON_DELEGADO on DEFINICION_REMESA (DELEGADO_ID);
