alter table CICLO add constraint FK_CICLO_ON_COLECCION_ADJUNTOS foreign key (COLECCION_ADJUNTOS_ID) references COLECCION_ARCHIVOS_ADJUNTOS(ID);
alter table CICLO add constraint FK_CICLO_ON_DEPARTAMENTO foreign key (DEPARTAMENTO_ID) references DEPARTAMENTO(ID);
alter table CICLO add constraint FK_CICLO_ON_CONTRATO_INQUILINO foreign key (CONTRATO_INQUILINO_ID) references CONTRATO_INQUILINO(ID);
create index IDX_CICLO_ON_COLECCION_ADJUNTOS on CICLO (COLECCION_ADJUNTOS_ID);
create index IDX_CICLO_ON_DEPARTAMENTO on CICLO (DEPARTAMENTO_ID);
create index IDX_CICLO_ON_CONTRATO_INQUILINO on CICLO (CONTRATO_INQUILINO_ID);
