alter table CEDULA_HABITABILIDAD add constraint FK_CEDULA_HABITABILIDAD_ON_DEPARTAMENTO foreign key (DEPARTAMENTO_ID) references DEPARTAMENTO(ID);
create index IDX_CEDULA_HABITABILIDAD_ON_DEPARTAMENTO on CEDULA_HABITABILIDAD (DEPARTAMENTO_ID);
