alter table CONTRATO_INQUILINO add constraint FK_CONTRATO_INQUILINO_ON_PAGADOR foreign key (PAGADOR_ID) references PERSONA(ID);
create index IDX_CONTRATO_INQUILINO_ON_PAGADOR on CONTRATO_INQUILINO (PAGADOR_ID);
