alter table TEST1_NOTIFICACION add constraint FK_TEST1_NOTIFICACION_ON_PLANTILLA foreign key (PLANTILLA_ID) references PLANTILLA(ID);
create index IDX_TEST1_NOTIFICACION_ON_PLANTILLA on TEST1_NOTIFICACION (PLANTILLA_ID);
