alter table TEST1_DATO_DE_CONTACTO add constraint FK_TEST1_DATO_DE_CONTACTO_ON_PERSONA foreign key (PERSONA_ID) references TEST1_PERSONA(ID);
create index IDX_TEST1_DATO_DE_CONTACTO_ON_PERSONA on TEST1_DATO_DE_CONTACTO (PERSONA_ID);
