alter table TEST1_CONCEPTO_ADICIONAL_CONCEPTO_RECIBO change column CONCEPTO_ADICIONAL_ID CONCEPTO_ADICIONAL_ID__U54086 varchar(32)^
alter table TEST1_CONCEPTO_ADICIONAL_CONCEPTO_RECIBO add column CA_ID varchar(32) ;
