alter table CICLO add constraint FK_CICLO_ON_CONTRATO_INQUILINO foreign key (CONTRATO_INQUILINO_ID) references CONTRATO_INQUILINO(ID);
create index IDX_CICLO_ON_CONTRATO_INQUILINO on CICLO (CONTRATO_INQUILINO_ID);
