alter table FIANZA add constraint FK_FIANZA_ON_CONTRATO_INQUILINO foreign key (CONTRATO_INQUILINO_ID) references CONTRATO_INQUILINO(ID);
alter table FIANZA add constraint FK_FIANZA_ON_ESCANEO_ARCHIVO_ADJUNTO foreign key (ESCANEO_ARCHIVO_ADJUNTO_ID) references ARCHIVO_ADJUNTO(ID);
alter table FIANZA add constraint FK_FIANZA_ON_ESCANEO_SEGURO_ARCHIVO_ADJUNTO foreign key (ESCANEO_SEGURO_ARCHIVO_ADJUNTO_ID) references ARCHIVO_ADJUNTO(ID);
alter table FIANZA add constraint FK_FIANZA_ON_ESCANEO_FIANZA foreign key (ESCANEO_FIANZA_ID) references ARCHIVO_ADJUNTO(ID);
create index IDX_FIANZA_ON_CONTRATO_INQUILINO on FIANZA (CONTRATO_INQUILINO_ID);
create index IDX_FIANZA_ON_ESCANEO_ARCHIVO_ADJUNTO on FIANZA (ESCANEO_ARCHIVO_ADJUNTO_ID);
create index IDX_FIANZA_ON_ESCANEO_SEGURO_ARCHIVO_ADJUNTO on FIANZA (ESCANEO_SEGURO_ARCHIVO_ADJUNTO_ID);
create index IDX_FIANZA_ON_ESCANEO_FIANZA on FIANZA (ESCANEO_FIANZA_ID);
