alter table TEST1_UBICACION add constraint FK_TEST1_UBICACION_ON_DIRECCION foreign key (DIRECCION_ID) references TEST1_DIRECCION(ID);
create index IDX_TEST1_UBICACION_ON_DIRECCION on TEST1_UBICACION (DIRECCION_ID);
