alter table CICLO add constraint FK_CICLO_ON_COLECCION_ADJUNTOS foreign key (COLECCION_ADJUNTOS_ID) references COLECCION_ARCHIVOS_ADJUNTOS(ID);
create index IDX_CICLO_ON_COLECCION_ADJUNTOS on CICLO (COLECCION_ADJUNTOS_ID);
