alter table ASIGNACION_TAREA add constraint FK_ASIGNACION_TAREA_ON_ORDEN_TRABAJO foreign key (ORDEN_TRABAJO_ID) references ORDEN_TRABAJO(ID);
create index IDX_ASIGNACION_TAREA_ON_ORDEN_TRABAJO on ASIGNACION_TAREA (ORDEN_TRABAJO_ID);
