alter table TEST1_UBICACION change column DIRECCION_CP DIRECCION_CP__U50396 varchar(255)^
alter table TEST1_UBICACION change column DIRECCION_NUMERO DIRECCION_NUMERO__U10526 varchar(255)^
alter table TEST1_UBICACION change column DIRECCION_NOMBRE DIRECCION_NOMBRE__U47605 varchar(255)^
