alter table TEST1_CONCEPTO_RECIBO add constraint FK_TEST1_CONCEPTO_RECIBO_ON_INCREMENTO foreign key (INCREMENTO_ID) references TEST1_INCREMENTO(ID);
create index IDX_TEST1_CONCEPTO_RECIBO_ON_INCREMENTO on TEST1_CONCEPTO_RECIBO (INCREMENTO_ID);
