rename table TEST1_UBICACION to TEST1_UBICACION__U08756 ;
alter table TEST1_DEPARTAMENTO drop foreign key FK_TEST1_DEPARTAMENTO_ON_UBICACION;
alter table TEST1_DIRECCION drop foreign key FK_TEST1_DIRECCION_ON_UBICACION;
