alter table PROPIETARIO add constraint FK_PROPIETARIO_ON_PERSONA foreign key (PERSONA_ID) references PERSONA(ID);
alter table PROPIETARIO add constraint FK_PROPIETARIO_ON_CABECERA_DOCUMENTOS_ARCHIVO_ADJUNTO foreign key (CABECERA_DOCUMENTOS_ARCHIVO_ADJUNTO_ID) references ARCHIVO_ADJUNTO(ID);
alter table PROPIETARIO add constraint FK_PROPIETARIO_ON_CUENTA_BANCARIA foreign key (CUENTA_BANCARIA_ID) references CUENTA_BANCARIA(ID);
create index IDX_PROPIETARIO_ON_PERSONA on PROPIETARIO (PERSONA_ID);
create index IDX_PROPIETARIO_ON_CABECERA_DOCUMENTOS_ARCHIVO_ADJUNTO on PROPIETARIO (CABECERA_DOCUMENTOS_ARCHIVO_ADJUNTO_ID);
create index IDX_PROPIETARIO_ON_CUENTA_BANCARIA on PROPIETARIO (CUENTA_BANCARIA_ID);
