alter table INCREMENTO add constraint FK_INCREMENTO_ON_TIPO_COEFICIENTE foreign key (TIPO_COEFICIENTE_ID) references TEST1_TIPO_COEFICIENTE(ID);
create index IDX_INCREMENTO_ON_TIPO_COEFICIENTE on INCREMENTO (TIPO_COEFICIENTE_ID);
