alter table PARAMETRO_VALOR_ANEXO add constraint FK_PARAMETRO_VALOR_ANEXO_ON_ANEXO foreign key (ANEXO_ID) references ANEXO(ID);
create index IDX_PARAMETRO_VALOR_ANEXO_ON_ANEXO on PARAMETRO_VALOR_ANEXO (ANEXO_ID);
