alter table DEPARTAMENTO change column PROPIETARIO_ID PROPIETARIO_ID__U06674 varchar(32)^
alter table DEPARTAMENTO drop foreign key FK_DEPARTAMENTO_ON_PROPIETARIO;
drop index IDX_DEPARTAMENTO_ON_PROPIETARIO on DEPARTAMENTO ;
alter table DEPARTAMENTO add column PROPIETARIO_ID varchar(32) ;
