alter table DEFINICION_REMESA add constraint FK_DEFINICION_REMESA_ON_PROPIETARIO foreign key (PROPIETARIO_ID) references PROPIETARIO(ID);
create index IDX_DEFINICION_REMESA_ON_PROPIETARIO on DEFINICION_REMESA (PROPIETARIO_ID);
