alter table DEPARTAMENTO add constraint FK_DEPARTAMENTO_ON_PROPIETARIO foreign key (PROPIETARIO_ID) references PROPIETARIO(ID);
create index IDX_DEPARTAMENTO_ON_PROPIETARIO on DEPARTAMENTO (PROPIETARIO_ID);
