alter table REMESA add constraint FK_REMESA_ON_DEFINICION_REMESA foreign key (DEFINICION_REMESA_ID) references DEFINICION_REMESA(ID);
create index IDX_REMESA_ON_DEFINICION_REMESA on REMESA (DEFINICION_REMESA_ID);
