alter table CTA_DOCTOS_FOTOGRAFICOS add constraint FK_CTA_DOCTOS_FOTOGRAFICOS_ON_CICLO foreign key (CICLO_ID) references CICLO(ID);
create index IDX_CTA_DOCTOS_FOTOGRAFICOS_ON_CICLO on CTA_DOCTOS_FOTOGRAFICOS (CICLO_ID);
