alter table VALIDACION add constraint FK_VALIDACION_ON_PROPIETARIO foreign key (PROPIETARIO_ID) references PROPIETARIO(ID);
alter table VALIDACION add constraint FK_VALIDACION_ON_IMPUTACION_DOCUMENTO_IMPUTABLE foreign key (IMPUTACION_DOCUMENTO_IMPUTABLE_ID) references IMPUTACION_DOCUMENTO_IMPUTABLE(ID);
create index IDX_VALIDACION_ON_PROPIETARIO on VALIDACION (PROPIETARIO_ID);
create index IDX_VALIDACION_ON_IMPUTACION_DOCUMENTO_IMPUTABLE on VALIDACION (IMPUTACION_DOCUMENTO_IMPUTABLE_ID);
