alter table TEST1_COEFICIENTE add constraint FK_TEST1_COEFICIENTE_ON_TIPO_COEFICIENTE foreign key (TIPO_COEFICIENTE_ID) references TEST1_TIPO_COEFICIENTE(ID);
alter table TEST1_COEFICIENTE add constraint FK_TEST1_COEFICIENTE_ON_DEPARTAMENTO foreign key (DEPARTAMENTO_ID) references DEPARTAMENTO(ID);
create index IDX_TEST1_COEFICIENTE_ON_TIPO_COEFICIENTE on TEST1_COEFICIENTE (TIPO_COEFICIENTE_ID);
create index IDX_TEST1_COEFICIENTE_ON_DEPARTAMENTO on TEST1_COEFICIENTE (DEPARTAMENTO_ID);
