alter table TEST1_ORDEN_COBRO add constraint FK_TEST1_ORDEN_COBRO_ON_REALIZACION_COBRO foreign key (REALIZACION_COBRO_ID) references TEST1_REALIZACION_COBRO(ID);
alter table TEST1_ORDEN_COBRO add constraint FK_TEST1_ORDEN_COBRO_ON_RECIBO foreign key (RECIBO_ID) references RECIBO(ID);
create index IDX_TEST1_ORDEN_COBRO_ON_REALIZACION_COBRO on TEST1_ORDEN_COBRO (REALIZACION_COBRO_ID);
create index IDX_TEST1_ORDEN_COBRO_ON_RECIBO on TEST1_ORDEN_COBRO (RECIBO_ID);
