alter table UBICACION add constraint FK_UBICACION_ON_FOTO_FACHADA foreign key (FOTO_FACHADA_ID) references ARCHIVO_ADJUNTO(ID);
create index IDX_UBICACION_ON_FOTO_FACHADA on UBICACION (FOTO_FACHADA_ID);
