alter table REALIZACION_PAGO add constraint FK_REALIZACION_PAGO_ON_CUENTA_BANCARIA foreign key (CUENTA_BANCARIA_ID) references CUENTA_BANCARIA(ID);
create index IDX_REALIZACION_PAGO_ON_CUENTA_BANCARIA on REALIZACION_PAGO (CUENTA_BANCARIA_ID);
