alter table CONCEPTO_RECIBO add constraint FK_CONCEPTO_RECIBO_ON_CONCEPTO foreign key (CONCEPTO_ID) references CONCEPTO(ID);
alter table CONCEPTO_RECIBO add constraint FK_CONCEPTO_RECIBO_ON_PROGRAMACION_RECIBO foreign key (PROGRAMACION_RECIBO_ID) references PROGRAMACION_RECIBO(ID);
alter table CONCEPTO_RECIBO add constraint FK_CONCEPTO_RECIBO_ON_INCREMENTO foreign key (INCREMENTO_ID) references INCREMENTO(ID);
create index IDX_CONCEPTO_RECIBO_ON_CONCEPTO on CONCEPTO_RECIBO (CONCEPTO_ID);
create index IDX_CONCEPTO_RECIBO_ON_PROGRAMACION_RECIBO on CONCEPTO_RECIBO (PROGRAMACION_RECIBO_ID);
create index IDX_CONCEPTO_RECIBO_ON_INCREMENTO on CONCEPTO_RECIBO (INCREMENTO_ID);
