alter table ORDEN_PAGO add constraint FK_ORDEN_PAGO_ON_FACTURA_PROVEEDOR_AB foreign key (FACTURA_PROVEEDOR_AB_ID) references DOCUMENTO_IMPUTABLE(ID);
create index IDX_ORDEN_PAGO_ON_FACTURA_PROVEEDOR_AB on ORDEN_PAGO (FACTURA_PROVEEDOR_AB_ID);
