alter table OVERRIDE_CLAUSULA add constraint FK_OVERRIDE_CLAUSULA_ON_CLAUSULA foreign key (CLAUSULA_ID) references CLAUSULA(ID);
alter table OVERRIDE_CLAUSULA add constraint FK_OVERRIDE_CLAUSULA_ON_VERSION_APLICADA foreign key (VERSION_APLICADA_ID) references VERSION_CLAUSULA(ID);
alter table OVERRIDE_CLAUSULA add constraint FK_OVERRIDE_CLAUSULA_ON_IMPLEMENTACION_MODELO foreign key (IMPLEMENTACION_MODELO_ID) references IMPLEMENTACION_MODELO(ID);
create index IDX_OVERRIDE_CLAUSULA_ON_CLAUSULA on OVERRIDE_CLAUSULA (CLAUSULA_ID);
create index IDX_OVERRIDE_CLAUSULA_ON_VERSION_APLICADA on OVERRIDE_CLAUSULA (VERSION_APLICADA_ID);
create index IDX_OVERRIDE_CLAUSULA_ON_IMPLEMENTACION_MODELO on OVERRIDE_CLAUSULA (IMPLEMENTACION_MODELO_ID);
