alter table NOTIFICACION add constraint FK_NOTIFICACION_ON_PLANTILLA foreign key (PLANTILLA_ID) references PLANTILLA(ID);
alter table NOTIFICACION add constraint FK_NOTIFICACION_ON_CONTRATO_INQUILINO foreign key (CONTRATO_INQUILINO_ID) references CONTRATO_INQUILINO(ID);
create index IDX_NOTIFICACION_ON_PLANTILLA on NOTIFICACION (PLANTILLA_ID);
create index IDX_NOTIFICACION_ON_CONTRATO_INQUILINO on NOTIFICACION (CONTRATO_INQUILINO_ID);
