alter table INCREMENTO add column TIPO_COEFICIENTE_ID varchar(32) ;
alter table INCREMENTO add column CONCEPTO_RECIBO_ATRASOS_ID varchar(32) ;
alter table INCREMENTO add column UBICACION_ID varchar(32) ;
alter table INCREMENTO add column NOMBRE_TIPO varchar(255) ;
alter table INCREMENTO add column MES_ANNO_INDICE varchar(255) ;
alter table INCREMENTO add column FECHA_INCREMENTO date ;
alter table INCREMENTO add column MODO_REPARTICION integer ;
alter table INCREMENTO add column MESES_REPERCUSION_ATRASOS integer ;
alter table INCREMENTO add column VALOR_INDICE_PORCENTUAL double precision ;
alter table INCREMENTO add column IMPORTE_GLOGAL_INCREMENTO double precision ;
alter table INCREMENTO add column IMPORTE_ATRASOS double precision ;
alter table INCREMENTO add column MESES_ATRASOS integer ;
alter table INCREMENTO add column VALOR_BASE double precision ;
alter table INCREMENTO add column CONCEPTO_ID varchar(32) ;
alter table INCREMENTO add column IMPORTE double precision ;
alter table INCREMENTO add column DTYPE varchar(100) ;
alter table INCREMENTO add column VALOR_COEFICIENTE double precision ;
alter table INCREMENTO add column VALOR_INDICE double precision ;
alter table INCREMENTO add column INDICE_ANTERIOR double precision ;
