alter table ORDEN_PAGO add constraint FK_ORDEN_PAGO_ON_FACTURA_PROVEEDOR foreign key (FACTURA_PROVEEDOR_ID) references DOCUMENTO_IMPUTABLE(ID);
create index IDX_ORDEN_PAGO_ON_FACTURA_PROVEEDOR on ORDEN_PAGO (FACTURA_PROVEEDOR_ID);
