alter table CTA_DOCTOS_FOTOGRAFICOS add constraint FK_CTA_DOCTOS_FOTOGRAFICOS_ON_EVENTO foreign key (EVENTO_ID) references EVENTO(ID);
create index IDX_CTA_DOCTOS_FOTOGRAFICOS_ON_EVENTO on CTA_DOCTOS_FOTOGRAFICOS (EVENTO_ID);
