alter table ORDENANTE_REMESA add constraint FK_ORDENANTE_REMESA_ON_DEFINICION_REMESA foreign key (DEFINICION_REMESA_ID) references DEFINICION_REMESA(ID);
alter table ORDENANTE_REMESA add constraint FK_ORDENANTE_REMESA_ON_REMESA foreign key (REMESA_ID) references REMESA(ID);
create index IDX_ORDENANTE_REMESA_ON_DEFINICION_REMESA on ORDENANTE_REMESA (DEFINICION_REMESA_ID);
create index IDX_ORDENANTE_REMESA_ON_REMESA on ORDENANTE_REMESA (REMESA_ID);
