alter table COMP_OP_PROVEEDOR add constraint FK_COMP_OP_PROVEEDOR_ON_ORDEN_PAGO_ABONO foreign key (ORDEN_PAGO_ABONO_ID) references ORDEN_PAGO(ID);
create index IDX_COMP_OP_PROVEEDOR_ON_ORDEN_PAGO_ABONO on COMP_OP_PROVEEDOR (ORDEN_PAGO_ABONO_ID);
