alter table TEST1_RESERVA add constraint FK_TEST1_RESERVA_ON_COMERCIAL foreign key (COMERCIAL_ID) references COMERCIAL_OFERTAS(ID);
alter table TEST1_RESERVA add constraint FK_TEST1_RESERVA_ON_OFERTA foreign key (OFERTA_ID) references OFERTA(ID);
create index IDX_TEST1_RESERVA_ON_COMERCIAL on TEST1_RESERVA (COMERCIAL_ID);
create index IDX_TEST1_RESERVA_ON_OFERTA on TEST1_RESERVA (OFERTA_ID);
