alter table PROVEEDOR change column COMERCIAL_OFERTAS_ID COMERCIAL_OFERTAS_ID__U52401 varchar(32)^
alter table PROVEEDOR drop foreign key FK_PROVEEDOR_ON_COMERCIAL_OFERTAS;
drop index IDX_PROVEEDOR_ON_COMERCIAL_OFERTAS on PROVEEDOR ;
