alter table OFERTA add constraint FK_OFERTA_ON_COMERCIAL_ALQUILER foreign key (COMERCIAL_ALQUILER_ID) references COMERCIAL_OFERTAS(ID);
create index IDX_OFERTA_ON_COMERCIAL_ALQUILER on OFERTA (COMERCIAL_ALQUILER_ID);
