alter table COMERCIAL_OFERTAS add constraint FK_COMERCIAL_OFERTAS_ON_PROVEEDOR foreign key (PROVEEDOR_ID) references PROVEEDOR(ID);
create index IDX_COMERCIAL_OFERTAS_ON_PROVEEDOR on COMERCIAL_OFERTAS (PROVEEDOR_ID);
