alter table TEST1_ORDEN_COBRO add constraint FK_TEST1_ORDEN_COBRO_ON_CREDITOR foreign key (CREDITOR_ID) references PERSONA(ID);
create index IDX_TEST1_ORDEN_COBRO_ON_CREDITOR on TEST1_ORDEN_COBRO (CREDITOR_ID);
