alter table TEST1_CUENTA_DE_GASTO add constraint FK_TEST1_CUENTA_DE_GASTO_ON_TITULAR foreign key (TITULAR_ID) references PERSONA(ID);
alter table TEST1_CUENTA_DE_GASTO add constraint FK_TEST1_CUENTA_DE_GASTO_ON_PERSONA foreign key (PERSONA_ID) references PERSONA(ID);
create index IDX_TEST1_CUENTA_DE_GASTO_ON_TITULAR on TEST1_CUENTA_DE_GASTO (TITULAR_ID);
create index IDX_TEST1_CUENTA_DE_GASTO_ON_PERSONA on TEST1_CUENTA_DE_GASTO (PERSONA_ID);
