alter table TEST1_REGISTRO_PRESENCIAL add constraint FK_TEST1_REGISTRO_PRESENCIAL_ON_USUARIO foreign key (USUARIO_ID) references SEC_USER(ID);
create index IDX_TEST1_REGISTRO_PRESENCIAL_ON_USUARIO on TEST1_REGISTRO_PRESENCIAL (USUARIO_ID);
