alter table CONTRATO_INQUILINO add constraint FK_CONTRATO_INQUILINO_ON_CICLO foreign key (CICLO_ID) references CICLO(ID);
create index IDX_CONTRATO_INQUILINO_ON_CICLO on CONTRATO_INQUILINO (CICLO_ID);
