alter table ORDEN_PAGO add constraint FK_ORDEN_PAGO_ON_EMISOR_PERSONA foreign key (EMISOR_PERSONA_ID) references PERSONA(ID);
create index IDX_ORDEN_PAGO_ON_EMISOR_PERSONA on ORDEN_PAGO (EMISOR_PERSONA_ID);
