alter table ORDEN_PAGO add constraint FK_ORDEN_PAGO_ON_BENEFICIARIO_PERSONA foreign key (BENEFICIARIO_PERSONA_ID) references PERSONA(ID);
create index IDX_ORDEN_PAGO_ON_BENEFICIARIO_PERSONA on ORDEN_PAGO (BENEFICIARIO_PERSONA_ID);
