alter table DOCUMENTO_IMPUTABLE add constraint FK_DOCUMENTO_IMPUTABLE_ON_TITULAR_PERSONA foreign key (TITULAR_PERSONA_ID) references PERSONA(ID);
create index IDX_DOCUMENTO_IMPUTABLE_ON_TITULAR_PERSONA on DOCUMENTO_IMPUTABLE (TITULAR_PERSONA_ID);
